### ISSUE TITLE
Issues with List<> insert\remove\get

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#694] opened 2017-07-12 20:30 UTC
List<> insert\remove\get methods not working correctly. Have been trying to fix this, but no luck.

`List<char> list = new List<char> {'1','2','3','4','5','6','7','8','9','0'};`

list.Insert(5, 'a') returns '12345a12345' instead of '12345a67890'
list.GetRange(3,5) returns similar invalid data.
list.RemoveAt(4) returns similar invalid data.
list.RemoveRange(4, 3) blows up.

**Comment by jp2masa** [comment] 2017-07-12 20:53
Are you using the latest dev kit?

**Comment by JoDogger** [comment] 2017-07-12 21:11
Yes, updated before I ran my tests.

**Comment by JoDogger** [comment] 2017-07-14 13:19
So, is this a bug or a user error?

**Comment by jp2masa** [comment] 2017-07-14 13:29
This is a bug related to arrays I think. I can try fixing this today.

**Comment by jp2masa** [comment] 2017-07-15 01:15
This bug will be hard to fix. The current Array.Copy implementation just copies from source to destination, but it should check for array overlapping (which is the cause of the issue) and it should cast array items (which currently isn't needed and can be done later). The current implementation uses `rep movs`, which always copies memory bytes in the same direction, so it will be hard to fix, while keeping it fast.

**Comment by jp2masa** [comment] 2017-10-30 22:33
`Insert` and `RemoveAt` should be working now, the other ones are blocked by CosmosOS/IL2CPU#15.

**Comment by quajak** [comment] 2022-12-18 19:07
This should be fixed now

**Closed by quajak** 2022-12-18 19:07 UTC
Labels: Bug, Priority: Medium, Blocked
