### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#568] opened 2017-01-27 23:13 UTC
I edited this to make it more correct,
I'm getting a NullReferenceException.
```c#
2>	Error: Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Cosmos.IL2CPU.AppAssembler.GenerateVMTCode(HashSet`1 aTypesSet, HashSet`1 aMethodsSet, Func`2 aGetTypeID, Func`2 aGetMethodUID) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 1125
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 958
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 245
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
```

**Comment by jp2masa** [comment] 2017-01-27 23:16
Are you using the devkit or the userkit? Try finding the cause of the error commenting parts of your code.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:17
Devkit, and i have a lot of code to copypaste, so i will post the parts i think that cause the problem.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:22
And i think that it is somewhere in this file: https://github.com/StrobeOS/strobe/blob/master/src/strvmr/strlib/Firmware/BIOS.cs

**Comment by jp2masa** [comment] 2017-01-27 23:25
Try this code in a new kernel:
```csharp
byte[] byteArray = new byte[] { 0x2E, 0x2E, 0x2E };
Console.WriteLine(Encoding.ASCII.GetString(byteArray));

```

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:27
Sure, also now i am 100% sure that the problem is in the BIOS file because i make a new kernel with this code and i got the same error:
```c#
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Test
{
    public class Kernel : Sys.Kernel
    {
        BIOS test;
        protected override void BeforeRun()
        {
            test.Write("Cosmos boot OK!");
            test.Display();
        }

        protected override void Run()
        {
            test.Write("Input: ");
            var input = test.ReadLine();
            test.Write("Text typed: ");
            test.Write(input + "\n");
        }
    }
}
```
Now i will test the code and tell you the results.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:29
Visual Studio crashed, but it did compile.

**Comment by jp2masa** [comment] 2017-01-27 23:34
Try this:
```csharp
Console.WriteLine(Encoding.ASCII.GetByteCount("..."));
```

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:34
It's 
```c#
Encoding.ASCII.GetBytes()
```

**Comment by jp2masa** [comment] 2017-01-27 23:36
Maybe you can replace it with BitConverter.GetBytes()

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:38
Sure, but wouldn't this make it run faster?
```c#
byte[] GetBytes(string s)
{
    byte[] ret = new byte[s.Length];
    for (int i = 0; i < s.Length; i++)
        ret[i] = (byte)s[i];
    return ret;
}
```

**Comment by jp2masa** [comment] 2017-01-27 23:39
That's probably the best way to do it.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:42
Yea that error is fixed, now i hope i won't run into any other errors.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:45
Now i get this error...
```c#
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidSystemCollectionsGenericList1SystemByteInsertRangeSystemInt32SystemCollectionsGenericIEnumerable1SystemByte': System.Exception: Error interpreting stacktypes for IL_006C: Bne_Un ---> System.Exception: Comparing types 'System.Collections.Generic.ICollection`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Collections.Generic.List`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' not supported!
1>	   at Cosmos.IL2CPU.ILOpCodes.OpBranch.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpBranch.cs:line 173
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 413
```

**Comment by jp2masa** [comment] 2017-01-27 23:49
This error has a simple fix, but I need to check one thing first.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:49
That was because i used:
```c#
List<byte> something = new List<byte>();
something.AddRange(someByteArray);
```
I replaced that code with
```c#
List<byte>something = new List<byte>();
foreach(byte b in someByteArray)
    something.Add(b);
```

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:50
The errors keep coming, but i don't have an idea on how to do this..
```c#
4>	Error: Exception: System.Exception: Original method argument $this is a reference type. Plug attribute first argument is not an argument type, nor was it marked with ObjectPointerAccessAttribute! Method: SystemInt32SystemArrayget_Rank Parameter: aThis
4>	   at Cosmos.IL2CPU.AppAssembler.GenerateMethodForward(MethodInfo aFrom, MethodInfo aTo) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 1295
4>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 906
4>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 245
4>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
```

**Comment by jp2masa** [comment] 2017-01-27 23:51
That one is easy: just go to ArrayImpl.cs in Cosmos.Core.Plugs and add  [ObjectPointerAccess] to the first argument of get_Rank()

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:53
Did you mean "Cosmos.Core.Plugs.System"?

**Comment by jp2masa** [comment] 2017-01-27 23:54
Yes

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:54
I found this
```c#
        public static unsafe int get_Rank(int* aThis)
        {
            return 1;
        }
```

**Comment by jp2masa** [comment] 2017-01-27 23:54
`public static unsafe int get_Rank(int* aThis)` should be `public static unsafe int get_Rank([ObjectPointerAccess]int* aThis)`

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:55
Ok, compiling now, i hope it works.

**Comment by mihail-mojsoski** [comment] 2017-01-27 23:59
So, now i have to do the same with GetLower?
```c#
2>	Error: Exception: System.Exception: Original method argument $this is a reference type. Plug attribute first argument is not an argument type, nor was it marked with ObjectPointerAccessAttribute! Method: SystemInt32SystemArrayGetLowerBoundSystemInt32 Parameter: aThis
2>	   at Cosmos.IL2CPU.AppAssembler.GenerateMethodForward(MethodInfo aFrom, MethodInfo aTo) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 1295
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 906
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 245
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252

```

**Comment by jp2masa** [comment] 2017-01-28 00:00
Yes

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:01
Wait there are pointers in c#?

**Comment by jp2masa** [comment] 2017-01-28 00:03
Yes, they need to be used in unsafe context.

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:04
I understand how unsafe works now.

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:05
How did i get a NullReferenceException?
```c#
2>	Error: Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Cosmos.IL2CPU.AppAssembler.GenerateVMTCode(HashSet`1 aTypesSet, HashSet`1 aMethodsSet, Func`2 aGetTypeID, Func`2 aGetMethodUID) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 1125
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 958
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 245
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\crack\Desktop\os\cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
```

**Comment by jp2masa** [comment] 2017-01-28 00:11
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.IL2CPU/AppAssembler.cs#L1118
Replace that line with:
```
if (xNewMethod != null)
{
    xMethod = xNewMethod;
}
```

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:17
Wow, your response time is so fast and you fixed every bug. You are an expert at this.

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:17
Now let's see if more bugs pop up.

**Comment by jp2masa** [comment] 2017-01-28 00:19
I'm new at this, some fixes may cause unexpected behaviour, I'd need to debug to check what was happening on that NullReferenceException to make sure nothing strange will happen.

**Comment by jp2masa** [comment] 2017-01-28 00:22
I'm 99% sure that is because of the null reference exception, the interfaces weren't declared. Do you have code that I can test and will throw that exception?

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:23
Clone this repo: https://github.com/StrobeOS/os

**Comment by jp2masa** [comment] 2017-01-28 00:23
Maybe it has to do with some method you are using on a List\<byte\> but I'll check it.

**Comment by mihail-mojsoski** [comment] 2017-01-28 00:23
The code i'm trying to boot is in core.

**Comment by jp2masa** [comment] 2017-01-28 00:24
ok, I'll try it

**Comment by mihail-mojsoski** [comment] 2017-01-28 17:39
So, any news? Is it fixable?

**Comment by jp2masa** [comment] 2017-01-28 17:46
The problem is: Array is the base class of byte[], and Array implements IEnumerable, which declares GetEnumerable, which is implemented in Array, but it's not on DeclaredMethods. It's in runtime methods, but then get_Count, which should exist, doesn't exist in declared nor runtime methods, I'll need to check this better.

**Comment by mihail-mojsoski** [comment] 2017-01-28 18:02
Ok, thanks. And i have a question.. does loading files as bytes from fat work?

**Comment by jp2masa** [comment] 2017-01-28 18:12
I don't know if it works on master, but if you use the changes from the branch of PR #522 it works for sure, just clone it and copy the source/Cosmos.System/Filesystem folder to your Cosmos sources.

**Comment by mihail-mojsoski** [comment] 2017-01-28 18:16
If it doesn't work, i will do that, and so far how is the problem going? Is it fixable?

**Comment by jp2masa** [comment] 2017-01-28 18:21
It's fixable, but I'll need to check this better to understand how to fix it in a good way.

**Comment by mihail-mojsoski** [comment] 2017-01-28 18:35
Thank you.

**Comment by jp2masa** [comment] 2017-01-28 19:54
Are you using LINQ?

**Comment by mihail-mojsoski** [comment] 2017-01-28 20:49
Not sure, probably not.

**Comment by mihail-mojsoski** [comment] 2017-01-28 20:51
In this file i "used" LINQ but actually never did use it.
https://github.com/StrobeOS/strobe/blob/master/src/strvmr/strlib/Hardware/Processor.cs

**Comment by jp2masa** [comment] 2017-01-28 20:54
What I can tell you is that you are using Linq in a byte array(byte[]).

**Comment by mihail-mojsoski** [comment] 2017-01-28 20:59
I removed `using System.LINQ;` and nothing changed because i wasn't using it in that file, i will check if i have been using it in other files.

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:04
I only use:
```c#
System
System.Collections.Generic
System.Text
System.IO
```
And i reference the projects:
```c#
https://github.com/StrobeOS/strobe/tree/master/src/strvmr/strlib
https://github.com/StrobeOS/strobe/tree/master/src/strvmr/strdif
```

**Comment by jp2masa** [comment] 2017-01-28 21:12
I see it has no LINQ from System.Linq, but a byte array is being treated as a generic type, and I'm almost sure that happens because of LINQ, check the operations you're doing with byte arrays and see if any of them seem to be using generic methods.

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:12
I use List<byte> a lot of times.

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:13
Maybe that is why?

**Comment by jp2masa** [comment] 2017-01-28 21:14
It has nothing to do with List, it is a generic method that is being used on byte[]

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:15
How can i check that?

**Comment by jp2masa** [comment] 2017-01-28 21:17
Usually you can easily see if a method is generic or not, for example, if you use the operator `=>` maybe you are using LINQ, if you use the Count property, it's from a generic interface(IList I think).

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:18
I do use Count, but not from LINQ, from List.

**Comment by jp2masa** [comment] 2017-01-28 21:24
Maybe the problem is ToArray(). Try this:
```csharp
List<byte> list = new List<byte>();
list.Add(0x4);
list.Add(0x5);
list.Add(0x6);
Console.WriteLine(list.ToArray()[1]);
```

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:28
I need to reinstall Cosmos, so this may take a few minutes.

**Comment by mihail-mojsoski** [comment] 2017-01-28 21:38
It compiled correctly.

**Comment by jp2masa** [comment] 2017-01-31 19:39
Try this:
```csharp
byte[] arr = new byte[] { 1, 2, 3 };
List<byte> n = new List<byte>(arr);
Console.WriteLine(n[0]);
```

**Comment by zarlo** [comment] 2017-02-02 10:44
i thing BitConverter needs to be pluged

**Comment by jp2masa** [comment] 2017-02-02 13:41
BitConverter doesn't need any plug, we have tests for it and it works fine.

**Comment by mihail-mojsoski** [comment] 2017-02-02 19:53
Sorry i wasn't able to do that because i was at school. I will try to compile it tomorrow because it's late.

**Comment by mihail-mojsoski** [comment] 2017-02-04 22:29
```C#
2>	Error: Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrived.
2>	   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
2>	   at Cosmos.IL2CPU.ILScanner.ScanType(Type aType) in C:\Users\crack\Desktop\p\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 640
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\crack\Desktop\p\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 668
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\crack\Desktop\p\cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 243
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\crack\Desktop\p\cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
```
Sorry, i wasn't on for a while.

**Comment by jp2masa** [comment] 2017-02-04 23:07
There's an issue about an error like that, I don't think that it's high priority for now. In your code, replace your calls to new List\<T\>(Array) with a 'for'.

**Comment by mihail-mojsoski** [comment] 2017-02-06 15:20
Sure, i will tell you if i run into more issues.

**Comment by mihail-mojsoski** [comment] 2017-02-06 15:37
I still get this error from before...
```
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(35,5): error : C:\Users\crack\Desktop\p\core\kernel\bin\Debug\kernel.boot.asm:231760: error: symbol `VMT__TYPE_ID_HOLDER__System_Collections_Generic_IEqualityComparer_1___System_Int32__ASM_IS__mscorlib' undefined
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(35,5): error : C:\Users\crack\Desktop\p\core\kernel\bin\Debug\kernel.boot.asm:285927: error: symbol `VMT__TYPE_ID_HOLDER__System_Collections_Generic_IEqualityComparer_1___System_Int32__ASM_IS__mscorlib' undefined
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(35,5): error : Error occurred while invoking NAsm.
```

**Comment by jp2masa** [comment] 2017-02-06 17:10
Remove the 'if (xNewMethod != null)'. You'll still get an error, because you are using generic methods on arrays somehow.

**Comment by mihail-mojsoski** [comment] 2017-02-06 19:43
Can you tell me where it could be?

**Comment by jp2masa** [comment] 2017-02-06 19:56
Maybe LINQ, but probably there are other ways of using generic method on arrays.

**Comment by mihail-mojsoski** [comment] 2017-02-06 19:59
Will this ever be fixed?

**Comment by jp2masa** [comment] 2017-02-06 20:02
When netcore gets merged to master, I can take a look at this.

**Comment by mihail-mojsoski** [comment] 2017-02-06 20:13
Thank you for that information.

**Comment by fanoI** [comment] 2017-02-08 16:28
I'm lost a little what is the issue but the NullPointException (that is the title of the issue) was true in my opinion:

```
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Test
{
    public class Kernel : Sys.Kernel
    {
        BIOS test; // test is implicitly null
        protected override void BeforeRun()
        {
            test.Write("Cosmos boot OK!"); // test is null!
            test.Display();
        }

        protected override void Run()
        {
            test.Write("Input: ");
            var input = test.ReadLine();
            test.Write("Text typed: ");
            test.Write(input + "\n");
        }
    }
}
```

The correct version would be:

```
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Test
{
    public class Kernel : Sys.Kernel
    {
        BIOS test = new BIOS(); // test is correctly inizialized
        protected override void BeforeRun()
        {
            test.Write("Cosmos boot OK!");
            test.Display();
        }

        protected override void Run()
        {
            test.Write("Input: ");
            var input = test.ReadLine();
            test.Write("Text typed: ");
            test.Write(input + "\n");
        }
    }
}
```

**Comment by mihail-mojsoski** [comment] 2017-02-08 18:57
Well actually that isn't the issue, because the code changed a lot since then, and i am trying to boot:
```c#
using StrobeVM.DIF;
using Sys = Cosmos.System;

namespace kernel
{
    public class Kernel : Sys.Kernel
    {
        StrobeVM.Firmware.Kernel kernel;
        protected override void BeforeRun()
        {
            kernel = new StrobeVM.Firmware.Kernel(1024);
            kernel.Start(new DIFFormat().Load(HelloWorld()));
        }

        public static byte[] HelloWorld()
        {
            return new byte[]
            {
                        0x0,0x4,0x1c,0xfe,0xc,0xff, // define 0x1c with size 0xc ( the size of "Hello World\n")
			0x0,0x5,0x1c,0xfe, // add data to 0x1c (this is actually 1 instruction not 3, until 0xff)
			0x48,0x65,0x6c,0x6c,0x6f,0x20, // "Hello "
			0x77,0x6f,0x72,0x6c,0x64,0xa,0xff, // "World\n"
			0x0,0x9,0x1,0xfe,0x1c,0xff, // put the address of 0x1c in 0x1
			0x0,0xa,0x1,0xff, // define the label 0x1
			0x0,0x6,0x1,0xff, // write to buffer (takes 0x1)
			0x0,0x6,0x2,0xff, // display buffer to console
		        0x0,0x5,0x2,0xfe,0x0,0xff, // make 0x2 be 0x0
		        0x0,0xb,0x1,0x2,0xff, // goto label 0x1 (if 0x2 is 0x0)
		        0x0,0x5,0x1,0xfe,0x0,0xff, // make 0x1 be 0x0
			0x0,0x6,0x0,0xff // exit with error code (takes 0x1)
            };
        }

        protected override void Run()
        {
            kernel.Step();
        }
    }
}
```

**Comment by jp2masa** [comment] 2017-02-21 19:09
I'll close this issue and open a new issue about this. The problem here is using generics on arrays.
This means that when you have a variable or argument of type IEnumerable\<T\>, IList\<T\> or ICollection\<T\>, they can be an array, with limited functionality. The problem is that array doesn't implement these interfaces, their implementations is on a separate class called SZArrayHelper. This needs to be handled by the compiler, but we don't handle it currently.

**Closed by jp2masa** 2017-02-21 19:09 UTC
