### ISSUE TITLE
Yasm crash on QEMU configuration build

### ISSUE THREAD

**Issue by alexander-sil** [CosmosOS/Cosmos#2492] opened 2022-11-26 17:52 UTC
**Exception**
MSB6006: "yasm.exe" exited with code -1073741515.

**Visual Studio Output Logs**
Build started...
1>------ Build started: Project: Aembedded, Configuration: Debug Any CPU ------
1>Aembedded -> C:\Users\User\C# Code\Aembedded\bin\Debug\net6.0\Aembedded.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\User\C# Code\Aembedded\bin\Debug\net6.0\Aembedded.dll
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.INT3Label'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:01:47.3177071
1>-g null -f bin -o bin\Debug\net6.0\Aembedded.bin -dBIN_COMPILATION -O1 bin\Debug\net6.0\Aembedded.asm
1>C:\Users\User\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(229,9): error MSB6006: "yasm.exe" exited with code -1073741515.
1>Yasm task took 00:00:00.2224866
1>Done building project "Aembedded.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Screenshots**
![image](https://user-images.githubusercontent.com/93575945/204102287-6699e575-8a3b-48e2-85b1-2033f681c673.png)

**Context**
Before posting please confirm that the following are in order
[X] Both Cosmos VS Extensions are installed
[X] In the NuGet Package Manager "Include prerelease" is selected
[X] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[X] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by MishaTY** [comment] 2022-11-26 18:26
Duplicate of #2102 #2127 #2172 #2321 #2334

**Closed by MishaTY** 2022-11-26 18:26 UTC
Labels: Area: Visual Studio Integration, Area: Build
