### ISSUE TITLE
CAN SOMEONE PLEASE JUST MAKE THE EXE WITH THIS UPDATE?!

### ISSUE THREAD

**Issue by BioShot** [CosmosOS/Cosmos#2242] opened 2022-05-23 19:23 UTC
Im trying to install Cosmos. And I have a fixed version and nobody will build it. Here is the fixed iss. Can somebody just compile that to exe form?

https://github.com/CosmosOS/Cosmos/pull/2184/commits/6e7f01709e7ec4c04e156fb82d5df24d4315279d

**Comment by TaromaruYuki** [comment] 2022-05-23 19:35
Build it yourself? There's instructions on building and installing the dev kit.

**Comment by BioShot** [comment] 2022-05-23 19:36
I've tried

**Comment by BioShot** [comment] 2022-05-23 19:36
It just wont work on my pc. I've gone to issue pages and done everything. But it still doesn't work.

**Comment by TaromaruYuki** [comment] 2022-05-23 19:41
What's the issue? Is a error happening while building? Is your pc not capable of building it?

I made a build maybe 15 minutes ago and only had one easy to fix issue.

I can make a build later when I get home, I just wanna make sure the issue isn't a big one.

**Comment by BioShot** [comment] 2022-05-23 19:42
No, Its just its old(8 yr). I have it on windows 10. But I can't use the SWBEMLocator object. Whats your build?

**Comment by BioShot** [comment] 2022-05-23 19:43
If it removes swbemlocator, send it to me.

**Comment by TaromaruYuki** [comment] 2022-05-23 19:52
My laptop is a little older than that and I built it fine. (Core i3)

I haven't modified anything and I just pulled earlier today.

I can do a build just give me about a hour.

**Comment by BioShot** [comment] 2022-05-23 19:54
Thanks! Yea, Mine is an i7. But. It says some class not registered for SWBEMLocator.  So, Thanks!

**Comment by BioShot** [comment] 2022-05-23 19:55
I was also looking at your profile and saw that you knew c++. And liked gakkou gurashi. Just so you know. C++ Is the same as c. So if you wanted to ever use c. You can.

**Comment by TaromaruYuki** [comment] 2022-05-23 21:10
I'm assuming you tried this solution, right? I found a decent amount of solutions for your problem.

```
cd /d %windir%\system32\wbem
for %i in (*.dll) do RegSvr32 -s %i
for %i in (*.exe) do %i /RegServer
```

From what I see the FSWbemLocator is used in the `IsAppRunning` which checks if you have specific apps running. That can be pretty important.

I would try that first, restart your pc, and then try to build. If not, please tell me your results. :)

**Comment by BioShot** [comment] 2022-05-24 17:42
It gave me the error that RegServer does not exist.

**Comment by BioShot** [comment] 2022-05-24 17:43
I just need an exe. If you could put any working builds without swbemlocator that would be great :)

**Comment by Kiirx** [comment] 2022-05-25 16:11
mines is also 8 years old, and it compiles fine, on linux and on windows, we could give you this exe but this would be too easy, could you just give us the complete error? also,
![image](https://user-images.githubusercontent.com/43090601/170308397-94c6791f-1e75-4c7e-ae12-1a9cc38202b9.png)
dont put titles like that like you're mad at smth, we see this issue like the others.

**Comment by BioShot** [comment] 2022-05-25 16:13
I know it would be easy. But I am mad. I just want to use cosmos.

**Comment by Kiirx** [comment] 2022-05-25 16:14
> I know it would be easy. But I am mad. I just want to use cosmos.

ok but I would like to see the full log

**Comment by BioShot** [comment] 2022-05-25 16:16
It wont give me a log. Could you please just make the exe

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kiirx** [comment] 2022-05-25 16:17
it always gives you a log

**Comment by BioShot** [comment] 2022-05-25 16:18
It wont for me. Can't you just make it. It doesn't have to be hard.

**Comment by BioShot** [comment] 2022-05-25 16:21
I'm not lazy. It's been 5 months since I've tried cosmos. I've been back and fourth. I have not given up yet.

**Comment by Kiirx** [comment] 2022-05-25 16:21
then give me the log, if you're using devkit, theres a log, if you're using userkit, then go to the devkit.

**Comment by BioShot** [comment] 2022-05-25 16:25
I'm not home right now. But It seems like your the lazy one. If there is someone that can build I can use it

**Comment by Kiirx** [comment] 2022-05-25 16:27
> I'm not home right now. But It seems like your the lazy one. If there is someone that can build I can use it

hahahahahahahahha, ur so funny, u open an issue to tell us to make for you an exe, without trying further and you say im the lazy one? good one

**Comment by BioShot** [comment] 2022-05-25 16:29
```
Dude I have almost broke my pc to get this installed. I have been a lot of people for help. I'm the only one with this problem
```

**Comment by BioShot** [comment] 2022-05-25 16:30
https://github.com/CosmosOS/Cosmos/pull/2184

**Comment by BioShot** [comment] 2022-05-25 16:39
There should be some videos in those. I can't try it because I'm not home. I will be on Sunday is there any builds for Mac?

**Comment by Kiirx** [comment] 2022-05-25 17:25
nope, see https://github.com/CosmosOS/Cosmos/pull/2039

**Comment by BioShot** [comment] 2022-05-25 22:12
im on mac rn. i just need a build for windows

**Comment by BioShot** [comment] 2022-05-27 03:33
My pc just wont work for somethings. But, there are "nice" people out there that will build things peoples computers just can't. Thats called good customer service.

**Comment by zarlo** [comment] 2022-05-27 06:07
if you are on mac then how will a window build help you

**Comment by BioShot** [comment] 2022-05-27 16:10
because im not home. I will be Saturday


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TaromaruYuki** [comment] 2022-05-27 17:47
> ```
> cd /d %windir%\system32\wbem
> for %i in (*.dll) do RegSvr32 -s %i
> for %i in (*.exe) do %i /RegServer
> ```

Have you tried doing this? I never heard back.

The problem isn't with Cosmos, some files on your pc are corrupted. Please try the above, else go to Microsoft support.

My laptop is 12 years old and can compile Cosmos just fine, so it's the installation of Windows.

**Comment by BioShot** [comment] 2022-05-27 18:04
I have my pc may just not be able to do certain. Things

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TaromaruYuki** [comment] 2022-05-27 21:35
So you got in a live chat with someone at Microsoft and they remotely connected to your pc? That's about all I can really say now, it's not a Cosmos problem.

**Comment by BioShot** [comment] 2022-05-27 21:37
No. I don't really know what to do now. all your solutions have failed. Can you please just build it? its easier for everybody. there is someone else who doesn't have a build. I know that because he also had my same error

**Comment by BioShot** [comment] 2022-05-27 21:40
Aren't people supposed to fix issues? You can fix this one by building it

**Comment by zarlo** [comment] 2022-05-27 22:07
you need to build it your self

**Comment by BioShot** [comment] 2022-05-27 22:09
I've tried that for 3 mounths

**Comment by BioShot** [comment] 2022-05-27 22:10
It's like you don't want people using cosmos

**Comment by zarlo** [comment] 2022-05-28 00:19
if you are unable to build the dev kit just use the user kit

**Comment by BioShot** [comment] 2022-05-28 02:55
I can’t lol. Remember swbemlocator does not exist

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kiirx** [comment] 2022-05-28 06:50
Well, you don't want us to help you by giving the full error logs

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BioShot** [comment] 2022-05-28 14:03
Ok, So when i install it. I remember  the error it didn't give me much. But it did give me this:
Error: SWBEMLocator class not registered and that's all. I spent hour's trying to find a solution. Thats all it gave me

**Comment by BioShot** [comment] 2022-05-28 18:45
I am back home on my windows pc. Can someone give me an executable?

**Comment by valentinbreiz** [comment] 2022-05-30 04:46
Hello @BioShot I can try to help you what do you want exactly?
A new build of the userkit from the source code?

**Comment by BioShot** [comment] 2022-05-30 04:49
Yes, i made a change to cosmos.iss.
Can you build it with that change?
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Arawn-Davies** [comment] 2022-07-05 19:29
No need for this negativity. Closing this issue. Not an issue with Cosmos, as it appears you're the only one with this issue and it's not a Cosmos-related issue either.

**Closed by Arawn-Davies** 2022-07-05 19:29 UTC
Labels: Area: Installer

**Comment by BioShot** [comment] 2022-07-09 19:52
> Hello @BioShot I can try to help you what do you want exactly? A new build of the userkit from the source code?

sure, That would work.

**Comment by BioShot** [comment] 2022-07-09 19:52
> No need for this negativity. Closing this issue. Not an issue with Cosmos, as it appears you're the only one with this issue and it's not a Cosmos-related issue either.

Wrong, There was another person with the issue. Look at my past  issues.

**Comment by tails1154** [comment] 2025-12-03 05:17
install linux then build it
