### ISSUE TITLE
Cosmos VFS Bug

### ISSUE THREAD

**Issue by ADev531** [CosmosOS/Cosmos#2642] opened 2023-04-13 07:07 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
I Developing os with C#, with vfs

#### Expected Behaviour - What do you think that should happen?
reads file and prints.

#### Actual Behaviour - What unexpectedly happens?
vmware, it works. but not in real machine

#### Reproduction - How did you get this error to appear?
use cosmos vfs example in gocosmos.org

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit, release "first version of cosmos on 2022"

**Comment by GoldenretriverYT** [comment] 2023-04-13 08:04
This issue should be closed as its a duplicate of #2266

**Closed** 2023-04-16 18:52 UTC
Labels: Bug
