### ISSUE TITLE
Regex Crash

### ISSUE THREAD

**Issue by djlw78** [CosmosOS/Cosmos#911] opened 2018-02-25 18:36 UTC
#### Reproduction - Type the following code in run
` Regex regex = new Regex(@"\d+");
        Match match = regex.Match("Dot 55 Perls");
        if (match.Success)
        {
            Console.WriteLine(match.Value);
        }
`

#### Version - ** DEV KIT ** (edit: was userkit I actually use Aura's version but it follows the same)

**Comment by jp2masa** [comment] 2018-02-25 21:45
This is a duplicate of #588.

**Closed by jp2masa** 2018-02-25 21:45 UTC
Labels: Duplicate
