### ISSUE TITLE
Problem with calculator C#

### ISSUE THREAD

**Issue by BaRRaKudaRain** [CosmosOS/Cosmos#689] opened 2017-07-03 13:18 UTC
I want to add a calculator to my system. And getting IL2CPU error! HEEEEEEEELP! PLEASE!
There non working code:
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace BaRRaKudaDOS
{
public class Kernel : Sys.Kernel
{
protected override void BeforeRun()
{
Console.WriteLine("Starting...");
Console.WriteLine("BaRRaKudaDOS Started");
}

    protected override void Run()
    {
        Console.BackgroundColor = ConsoleColor.Black;
        Console.ForegroundColor = ConsoleColor.DarkGreen;
        Console.Write("Command$>");
        string cmd = Console.ReadLine();

        if (cmd == "help")
        {
            Console.WriteLine("List of supported commands:");
            Console.WriteLine("1. help - provides showing a list of commands.");
            Console.WriteLine("2. clear - clears console.");
            Console.WriteLine("3. calc - starts a calculator.");
            Console.WriteLine("4. ver - system version");
            Console.WriteLine("5. shutdown - shutting down system.");
            Console.WriteLine("6. ********** - easter egg.");
        }
        if (cmd == "ver")
        {
            Console.WriteLine("System version: BaRRaKudaDOS alpha v 0.12.");
        }
        else if (cmd == "clear")
        {
            Console.Clear();
        }
        else if (cmd == "calc")
        {
            double a, b;
            char c;
            Console.WriteLine("BaRRaKuda Calc v 1.0");
            Console.Write("Enter First Number: ");
            a = Double.Parse(Console.ReadLine());
            Console.Write("Enter Second Number: ");
            b = Double.Parse(Console.ReadLine());
            Console.Write("Enter Sign (+ - * /): ");
            c = Char.Parse(Console.ReadLine());
            switch (c)
            {
                case '+':
                    Console.WriteLine("{0}+{1}={2}", a, b ,a + b);
                    break;
                case '-':
                    Console.WriteLine("{0}-{1}={2}", a, b, a - b);
                    break;
                case '*':
                    Console.WriteLine("{0}*{1}={2}", a, b, a * b);
                    break;
                case '/':
                    Console.WriteLine("{0}/{1}={2}", a, b, a / b);
                    break;
                default:
                    Console.WriteLine("Unknown sign!");
                    break;
            }
        }
        else if (cmd == "shutdown")
        {
            Console.WriteLine("This function is temporary not supported!");
        }
        else
        {
            Console.WriteLine("Unknown command: ", cmd);
        }
    }
}

**Comment by jp2masa** [comment] 2017-07-03 13:56
From #688:
> The problem is probably this line:

Console.WriteLine("{0}%{1}={2}", a, b, a % b);

The % operator isn't implemented for double as it requires rounding, which is only available in SSE4. I have an implementation for it in a PR, but I'm splitting it as it's too big and it may take some time.

**Comment by BaRRaKudaRain** [comment] 2017-07-03 14:19
I removed this line, but i still getting error!

**Comment by jp2masa** [comment] 2017-07-03 14:29
What error are you getting? Probably the problem is `Double.Parse` or `Char.Parse`.

**Comment by BaRRaKudaRain** [comment] 2017-07-03 17:39
I think you're right.
There error:
Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  System.Number.NumberBufferToDouble(System.Byte*, &System.Double).

**Comment by fanoI** [comment] 2018-01-09 16:01
Double.Parse / TryParse() have been plugged closing this now.

**Closed by fanoI** 2018-01-09 16:01 UTC
