### ISSUE TITLE
remove dependence on .net 3.5 

### ISSUE THREAD

**Issue by liquidboy** [CosmosOS/Cosmos#554] opened 2017-01-01 06:28 UTC
Just raising this BUT expecting it to be pushed well low in your priorities ...

It would be nice to NOT have to require .NET 3.5 to develop with Cosmos. ..  

I'm a developer on a win10 machine and I really don't want to pollute my machine with .NET 3.5 if i can help it ...

**Comment by ROBLOXVIP735** [comment] 2017-01-01 06:37
It's .net 4 that you have to worry about. .NET 3.5 is really good.

On top of that it's needed for the builder as it's a great framework. You may have installed it if you have CS:GO.

**Comment by jp2masa** [comment] 2017-01-01 14:02
In fact, we're thinking about removing the dependency on .NET 3.5 soon.

**Comment by ROBLOXVIP735** [comment] 2017-01-01 23:58
Ahem why?

**Comment by jp2masa** [comment] 2017-01-02 00:15
.NET 3.5 was needed to read debug symbols, but now we are moving to .net core so .NET 3.5 libraries aren't compatible.

**Comment by jp2masa** [comment] 2017-01-17 20:05
This is a duplicate of #218.

**Closed by jp2masa** 2017-01-17 20:05 UTC
Labels: duplicate, enhancement, priority_medium
