### ISSUE TITLE
Can't make iso.

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#404] opened 2016-07-08 23:41 UTC
When I try to make an ISO SunflowerOSBoot -> Properties --> Cosmos ---> ISO image
this happens. 
`1>------ Build started: Project: SunFlowerOS-string, Configuration: Release Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.HAL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(216,17,216,25): warning CS0219: The variable 'ascii_14' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(217,17,217,25): warning CS0219: The variable 'ascii_15' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(218,17,218,25): warning CS0219: The variable 'ascii_16' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(219,17,219,25): warning CS0219: The variable 'ascii_21' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(226,17,226,26): warning CS0219: The variable 'ascii_251' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(227,17,227,26): warning CS0219: The variable 'ascii_252' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(228,17,228,26): warning CS0219: The variable 'ascii_253' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(229,17,229,26): warning CS0219: The variable 'ascii_254' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(230,17,230,26): warning CS0219: The variable 'ascii_255' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(231,17,231,26): warning CS0219: The variable 'ascii_256' is assigned but its value is never used
1>C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\Kernel.cs(232,17,232,21): warning CS0219: The variable 'abcs' is assigned but its value is never used
1>  SunFlowerOS-string -> C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll
2>------ Build started: Project: SunFlowerOS-stringBoot, Configuration: Debug x86 ------
2>  Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>  Executing command line "C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>  Working directory = 'C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\'
2>  Loaded : DebugEnabled
2>  Loaded : StackCorruptionDetectionEnabled
2>  Loaded : DebugMode
2>  Loaded : TraceAssemblies
2>  Loaded : DebugCom
2>  Loaded : UseNAsm
2>  Loaded : OutputFilename
2>  Loaded : EnableLogging
2>  Loaded : EmitDebugSymbols
2>  Loaded : IgnoreDebugStubAttribute
2>  Loaded : References
2>  Executing IL2CPU on assembly
2>  Error: Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.cdb' because it is being used by another process.
2>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>     at System.IO.File.InternalDelete(String path, Boolean checkHost)
2>     at System.IO.File.Delete(String path)
2>     at Cosmos.Debug.Common.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 73
2>     at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 209
2>  Loaded assemblies: 
2>  C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>  C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>  C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>  Errorred
2>  IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>  IL2CPU task took 00:00:01.7766454
2>Done building project "SunFlowerOS-stringBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
Build has been canceled.`

**Comment by jp2masa** [comment] 2016-07-09 00:18
Just close Visual Studio and open it again

**Comment by autoossite** [comment] 2016-07-09 01:36
Tried that like, 20 times

**Comment by autoossite** [comment] 2016-07-09 01:39
Now says:
'1>------ Build started: Project: SunFlowerOS-stringBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>	Working directory = 'C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.cdb' because it is being used by another process.
1>	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>	   at System.IO.File.InternalDelete(String path, Boolean checkHost)
1>	   at System.IO.File.Delete(String path)
1>	   at Cosmos.Debug.Common.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 73
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 209
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Release\SunFlowerOS-string.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.5227498
1>Done building project "SunFlowerOS-stringBoot.Cosmos" -- FAILED.
1>
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped =========='

**Comment by jp2masa** [comment] 2016-07-09 15:07
Close Visual Studio, then open it and instead of building do clean and then build.

**Comment by fanoI** [comment] 2016-07-10 11:50
The problem is that this file is in use:

1> Error: Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Selinna\Documents\Visual Studio 2015\Projects\SunFlowerOS-string\SunFlowerOS-string\bin\Debug\SunFlowerOS-stringBoot.cdb' because it is being used by another process.

sometimes Visual Studio left behind pieces of itself when it crashes / is forced closed that lock some files.

You can try to close Visual Studio and then check in task manager if there are "copies" of Visual Studio running yet or its subprocess "MSBuild.exe" and kill them too. If the file continues to be locked after this you have really two possibilities:

1. Reboot the machine
2. Install unlocker and go the file and right click on it you could find who is locking it and try to unlock the file

**Comment by autoossite** [comment] 2016-07-10 15:47
The only way I can fix it is restart visual studio. Every single time.

**Comment by autoossite** [comment] 2016-07-10 15:47
Not crashing or closing.

**Closed** 2017-05-23 23:30 UTC
Labels: complexity_low, priority_low
