### ISSUE TITLE
error when creating project

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#2615] opened 2023-03-25 10:15 UTC
this error comes when creating project in visual studio 2022

**Screenshots**

![error](https://user-images.githubusercontent.com/127417963/227711094-43349f51-d785-474b-ac57-f7c01778538d.png)

**Comment by zarlo** [comment] 2023-03-25 10:23
we need your build log to help

**Comment by randomusert** [comment] 2023-03-25 12:51
It gives the error when trying to create the project

la 25. maalisk. 2023 klo 12.24 zarlo ***@***.***) kirjoitti:

**Comment by randomusert** [comment] 2023-03-25 15:05
how do get it

la 25. maalisk. 2023 klo 14.51 Eetu Pajamäki ***@***.***)
kirjoitti:

**Comment by imadethisaccountsoicanmakeanissue** [comment] 2023-04-09 22:21
same but on the family computer

**Comment by quajak** [comment] 2023-04-11 19:14
Please provide more details on how you installed cosmos. Are you using devkit or userkit? Also check if there is anything in the VS logs.

**Comment by strike11** [comment] 2023-04-18 07:05
I have the same error

**Comment by quajak** [comment] 2023-04-20 01:38
According to Strike Mafia on the discord, the issue is with dotnet in the path and can be fixed by ensuring that the x86 version of dotnet is lower in the path.

![image](https://user-images.githubusercontent.com/8559822/233235486-cd6df507-c8e1-4ff8-abd8-e39d98ff467d.png)

**Closed** 2023-05-07 10:41 UTC
Labels: Area: Visual Studio Integration, Area: Build
