### ISSUE TITLE
WAV/PCM audio plays incorrectly.

### ISSUE THREAD

**Issue by Jspa2** [CosmosOS/Cosmos#2620] opened 2023-03-26 19:54 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
CAS

#### Expected Behaviour - What do you think that should happen?
It should play the audio correctly.

#### Actual Behaviour - What unexpectedly happens?
The audio sounds crackly, high pitched, and generally broken.

#### Reproduction - How did you get this error to appear?
I used [this WAV file](https://filebin.net/yx1o9jg9ilnw1oe1/song.wav), which is a 16 bit signed PCM with a sample rate of 6000 Hz and 1 channel, along with this code.
```
using Cosmos.HAL.Drivers.PCI.Audio;
using Cosmos.System.Audio.IO;
using Cosmos.System.Audio;
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using IL2CPU.API.Attribs;

namespace AudioPlayTest
{
    public class Kernel : Sys.Kernel
    {
        [ManifestResourceStream(ResourceName = "AudioPlayTest.song.wav")]
        private static byte[] data;

        protected override void BeforeRun()
        {
            var mixer = new AudioMixer();
            var audioStream = MemoryAudioStream.FromWave(data);
            var driver = AC97.Initialize(bufferSize: 4096);
            mixer.Streams.Add(audioStream);

            var audioManager = new AudioManager()
            {
                Stream = mixer,
                Output = driver
            };

            audioManager.Enable();

            Console.WriteLine("Playing");
        }

        protected override void Run()
        {
        }
    }
}
```
I have also tried with raw PCM files, different sample rates, stereo audio, 8-bit audio, etc, but all yield the same issue.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos [be7250e](https://github.com/CosmosOS/Cosmos/commit/be7250ec43730dcd9e78bafee1cec83576e1c22c)

**Comment by ascpixi** [comment] 2023-03-26 20:38
Currently, Cosmos does not have any resampling capabilities - resampling is a surprisingly difficult task, that requires DSP work. In order to resample the audio, we would need to create an interpolation filter, and then - for a high-quality re-sampler - implement a digital signal filter, and then run it in real-time - with IL2CPU lacking any optimization or vectorization capabilities, and the CAI running without any SSE help, that would bring the system to a crawl.

For this reason, you should resample your audio before-hand to a suitable sample rate - in AC97's case, 48000Hz, however, this sample rate is common across all modern audio device standards. You can either do this by implementing your own offline audio resampling engine, or by having the file be 48000Hz to begin with.

If you're experiencing crackle, that might be the cause of [buffer underruns](https://en.wikipedia.org/wiki/Buffer_underrun#Multimedia_playback). The only real fix for this is to improve the performance of Cosmos, as these underruns occur when the system cannot keep up with the audio device's interrupts, and skips some of the buffers to keep on running. Try decreasing the amount of concurrent channels you have in your audio mixer.

Please also note that mono audio will need to be up-sampled to stereo in order to be compatible with the AC97 - I'd recommend doing this beforehand as well. You can do this using CAI-provided facilities, such as with the `AudioBufferWriter` class, that will automatically convert the audio to your intended format, offloading the overhead of stereo up-mixing.

**Comment by Jspa2** [comment] 2023-03-26 21:43
@ascpixi thanks for the very detailed answer.

as for upsampling mono to stereo, i came up with this code, however the audio is still broken, so I would appreciate some insight:
```cs
var fromFormat = new SampleFormat(AudioBitDepth.Bits16, channels: 1, signed: true);
var toFormat   = new SampleFormat(AudioBitDepth.Bits16, channels: 2, signed: true);

var buffer = new AudioBuffer(data.Length * 2, toFormat);
var writer = new AudioBufferWriter(buffer, fromFormat);

for (int i = 0; i < data.Length / fromFormat.Size; i++)
{
    writer.Write(data, i, i * fromFormat.Size);
}

var audioStream = new MemoryAudioStream(toFormat, 48000, buffer.RawData);
```

**Comment by Jspa2** [comment] 2023-03-26 22:13
Disregard the above, there was an error in my audio file.

**Closed** 2023-03-27 00:22 UTC
Labels: Bug
