### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#947] opened 2018-04-09 09:14 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
Builder / Installer.

#### Expected Behaviour - What do you think that should happen?
To install successfully.

#### Actual Behaviour - What unexpectedly happens?
Does not install sucessfully.

#### Reproduction - How did you get this error to appear?
I ran installVS2017.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest commits of everything mentioned.

Here's the error log:
[ERROR_LOG.txt](https://github.com/CosmosOS/Cosmos/files/1889176/ERROR_LOG.txt)
What happened?

**Comment by Arawn-Davies** [comment] 2018-04-10 04:17
I'm not exactly sure 100% as I've been having this issue myself lately, not whilst building Cosmos but in a different scenario.

Also, in the future, please keep the default issue text as it allows us to see exactly what parts of Cosmos is failing and at what point in time that issue occured amongst other things. It makes solving issues a lot easier for us :)

**Comment by 365Tito** [comment] 2018-04-10 10:41
What is default issue text? @Arawn-Davies

**Comment by 365Tito** [comment] 2018-04-10 22:26
Oh, that form thing. Sorry, I didn't fill it. This is just a "simple" build error.
Anyways, the devkit commit I use is the latest one.
Expected behavior: To build.
Actual behavior: Doesn't build.
Area: Builder.

**Comment by Arawn-Davies** [comment] 2018-04-10 22:38
No worries :) I've got no idea why it's been happening, although I remember it working before the references were changed to $(CosmosRepoRoot)source\Cosmos.Debug.Kernel, no idea if that's what has caused it or how it resolves the references

I've forwarded the issue to others as I've got no idea how references are resolved with the variables, but in the meantime, if you're repos have been cloned correctly with the right directory tree,then you can try changing $(CosmosRepoRoot) on Line 24 of https://github.com/CosmosOS/IL2CPU/blob/9bb3b5b857a8c14a84c465b1d6d23380be737a0a/source/Cosmos.IL2CPU/Cosmos.IL2CPU.csproj#L24

to the following:
```
<ProjectReference Include="..\..\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" />
```  and see if that fixes the problem

**Comment by 365Tito** [comment] 2018-04-11 13:01
@Arawn-Davies doesn't solve my problem.

**Comment by 365Tito** [comment] 2018-04-11 18:36
@Arawn-Davies it gives out "missing reference or using" error now, so definitely can't connect it that way.
I think this is an issue with either IL2CPU or the builder itself.

**Comment by Arawn-Davies** [comment] 2018-04-13 23:01
@fanoI any idea what could be going wrong?
It's been happening a fair bit lately, but I have no idea why its happening only now, or how it can be fixed :/

**Comment by 365Tito** [comment] 2018-04-15 19:55
@Arawn-Davies @fanoI Finally I found something interesting.
The installation works after renaming the Cosmos directory to "Cosmos" instead of "COSMOS".
Seems the all caps somehow confuses the references.

**Comment by jp2masa** [comment] 2018-08-01 17:27
If anyone else hits this, it seems to be an issue with case sensitivity, probably caused by project restore (i.e. maybe the restore assets contain a path, but the real path now has a different casing). Running `dotnet restore -f` or removing the `obj` folders should fix it.

@365Tito It's working for you so I'm closing this, feel free to reopen the issue if you hit this again.

**Closed by jp2masa** 2018-08-01 17:27 UTC
