### ISSUE TITLE
unexpected exception during attach System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by AtomXZR** [CosmosOS/Cosmos#1365] opened 2020-06-20 09:04 UTC
![ERROR](https://user-images.githubusercontent.com/65809025/85197983-0a7bfa80-b30f-11ea-808e-4c780bee361c.PNG)
#### Actual Behaviour - What unexpectedly happens?
exception during attach

#### Reproduction - How did you get this error to appear?
after the build finished

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Version: User Kit
VMware: 15.5 Workstation Pro
Visual Studio Version: 2019

**Comment by EliaSulimanov** [comment] 2020-06-30 19:45
Please make sure your installation folder name is 'Cosmos', not 'Master-Cosmos'.

**Comment by Edersteiner** [comment] 2020-07-05 15:06
@EliaSulimanov could you explain more? I've been making a OS with Cosmos for about a year now and i just got this problem after reinstalling windows.

**Comment by EliaSulimanov** [comment] 2020-07-05 15:52
@Edersteiner Sure.
After cloning (or unzipping) the main branch, the folder that created (and contains the source code) named "Cosmos-master".
If this happens to you, than you should rename it to "Cosmos" (notice that "-master" were removed).
This may or may not fix the problem, but its the easiest first thing to try.

**Comment by Edersteiner** [comment] 2020-07-05 15:56
@EliaSulimanov I was using the User Kit. I figured that I should have tried the DevKit so im installing it now... It seems to be stuck on installing some visual studio worklflow thing

**Comment by EliaSulimanov** [comment] 2020-07-05 16:02
@Edersteiner Same rule applies for the devkit, make sure the folder name is correct.
It may seem stuck for a while, its installing things is the background. On my pc (low end), installation taking 20-30 minutes.

**Comment by quajak** [comment] 2020-07-05 18:02
I think the problem is being caused by a recent VS update (16.6.1), it should be fixed by in the devkit.

**Comment by Edersteiner** [comment] 2020-07-05 22:23
The DevKit does not have the same problem!

**Comment by quajak** [comment] 2020-07-06 12:37
Ok so this will be fixed by the next user kit, which will be released very soon.

**Closed by quajak** 2020-07-06 12:37 UTC
