### ISSUE TITLE
help il2cpu 

### ISSUE THREAD

**Issue by dannyoo7** [CosmosOS/Cosmos#1122] opened 2019-02-14 16:20 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
error 

#### Expected Behaviour - What do you think that should happen?
normal execution

#### Actual Behaviour - What unexpectedly happens?
the code doesnt update

#### Reproduction - How did you get this error to appear?
in the error log [only while i boot the item !]

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
(my code)
using System;
using System.Net.NetworkInformation;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        //basics
        protected override void BeforeRun()
        {
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("danny-OS geboot, druk op enter om verder tegaan.");
            Console.ReadLine();
        }

        protected override void Run()
        {
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("voer iets in");
            Console.WriteLine("");
            string invoer = Console.ReadLine();
            string[] splits = invoer.Split(" ");
            whatmessage(splits);
        }
        public void clear()
        {
            Console.Clear();
        }
        //werkt
        public void whatmessage(string[] invoer)
        {
            string command = command = invoer[0];
            if (command == "help")
            {
                worduitgevoerd("help");
                help();
            }
            else if (command == "ping")
            {
                worduitgevoerd("ping");
                ping(invoer);
            }
            else
            {
                Console.WriteLine("geen geldige command (druk op enter om verder te gaan)");
                Console.ReadLine();
                Run();
            }
        }
        //werkt
        public void help()
        {
            clear();
            Console.WriteLine("help - laat deeze lijst zien");
            Console.WriteLine("ping ip - kijkt of een ip online is");
            Console.ReadKey();
            Run();
        }
        public void worduitgevoerd(string uitgevoerd)
        {
            bool dev = true;
            if(dev == true)
            {
                Console.WriteLine(uitgevoerd +" word uitgevoerd");
                Console.ReadKey();
            }
        }
        //basics
        //ping
        public void ping(string[] invoer)
        {
            clear();
            //help google.com
            //0    1          overig
            string ipadress = invoer[1];
            Ping p1 = new Ping();
            PingReply PR = p1.Send(ipadress);
            if (!PR.Status.ToString().Equals("Success"))
            {
                Console.WriteLine("het is ipadress " + ipadress + " is werkend.");
            }
            else
            {
                Console.WriteLine("het is ipadress " + ipadress + " is ofline of niet werkend.");
            }
            Console.ReadKey();
            clear();
            Run();
        }
        //ping
    }
}

**Comment by Project-Magenta** [comment] 2019-02-16 02:32
what is the error?

**Comment by VisualDevelopment** [comment] 2019-03-03 06:49
Invalid issue format! Your issue is missing information.

**Comment by Project-Magenta** [comment] 2019-03-03 17:02
what?

**Comment by Project-Magenta** [comment] 2019-03-03 17:02
is this a joke?

**Comment by VisualDevelopment** [comment] 2019-03-05 11:31
Was my question/comment too robot-like? Sorry.

**Comment by Project-Magenta** [comment] 2019-03-08 18:15
but what is the error?

**Comment by adamstenbaek** [comment] 2019-03-29 23:03
Hello, @dannyoo7.
I can see that you are missing the most important part, the error itself. If you are using VS you should see the error in the "Error List", which normally is at the bottom of the screen.

What you have described also seems to be lacking in basic information.
1. The title is just "help il2cpu", a good title would look like: "IL2CPU creates an error when X"
2. `"Area of Cosmos - What area of Cosmos are we dealing with?"`. You simply wrote "error", if you were trying to do something with networking, you should have written "Networking" or "Network"
3. `"Expected Behaviour - What do you think that should happen?"`. A good thing to also write would be what you were trying to accomplish, like "It should run normally and obtain the HTML code for http://example.com/ then write it"
4. `"Actual Behaviour - What unexpectedly happens?"`. I don't really understand what "the code doesnt update" means, do you mean: "The code doesn't compile"? Also, it would be great if you could describe it a little more like "When I start debugging it will begin to build, but then it just stops and throws the error "X""
5. `"Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?"`. In here you posted your code, that is not what it is for, here you are supposed to write things like if you installed the User Kit or Dev Kit. And if you can get the version, then what version.

**Comment by quajak** [comment] 2021-01-22 11:46
Since we have received no further information, I am closing this issue.

**Closed by quajak** 2021-01-22 11:46 UTC
Labels: Pending User Response
