### ISSUE TITLE
Error Running Setup

### ISSUE THREAD

**Issue by mmcc1** [CosmosOS/Cosmos#471] opened 2016-09-17 17:19 UTC
I have downloaded the latest repo and have all the prerequisites installed.  Everything seems to go well with the build, but upon running as it moves to the 'Running Setup' stage, it throws an error.  Below is the output.  I've only kept the relevant portions:

> 
======================
Checking Prerequisites
======================

Note: This check only prerequisites for building, please see website for full list.
Checking for x86 run.
Checking Operating System
Check if User Kit Installer is already running.
Checking if Visual Studio is running.
Checking if Builder is already running.
Checking for Visual Studio 2015
Checking for Microsoft Visual Studio 2015 SDK - ENU
Checking for .NET 3.5 SP1
Checking for .NET 4.03
Checking for Inno Setup
Checking for Inno Preprocessor
Checking for VMware Workstation
Checking for VMware Player

=======================
Cleaning up VSIP Folder
=======================

Deleting build output directory.
  C:\Dev\Cosmos-master\Build\VSIP

================
Compiling Cosmos
================

Starting: C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe
  Params: /t:Clean "C:\Dev\Cosmos-master\source\Build.sln" /nologo /maxcpucount /p:Configuration="Debug" /p:Platform="Any CPU" /p:OutputPath="C:\Dev\Cosmos-master\Build\VSIP"
Build started 18/09/2016 00:00:11.
     1>Project "C:\Dev\Cosmos-master\source\Build.sln" on node 1 (Clean target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
     1>Project "C:\Dev\Cosmos-master\source\Build.sln" (1) is building "C:\Dev\Cosmos-master\source\Cosmos.Core.Memory\Cosmos.Core.Memory.csproj" (2) on node 1 (Clean target(s)).
     2>Project "C:\Dev\Cosmos-master\source\Cosmos.Core.Memory\Cosmos.Core.Memory.csproj" (2) is building "C:\Dev\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj" (3) on node 1 (Clean target(s)).
     
Time Elapsed 00:00:00.76

Starting: C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe
  Params: /t:Build "C:\Dev\Cosmos-master\source\Build.sln" /nologo /maxcpucount /p:Configuration="Debug" /p:Platform="Any CPU" /p:OutputPath="C:\Dev\Cosmos-master\Build\VSIP"
Build started 18/09/2016 00:00:12.
     1>Project "C:\Dev\Cosmos-master\source\Build.sln" on node 1 (Build target(s)).

     1>Project "C:\Dev\Cosmos-master\source\Build.sln" (1) is building "C:\Dev\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj" (3) on node 3 (default targets).
     3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data.SQLite, Version=1.0.99.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Dev\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj]
    

     1>Project "C:\Dev\Cosmos-master\source\Build.sln" (1) is building "C:\Dev\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj" (24) on node 4 (default targets).
    24>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. 
	
	
    
	
     9>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Dev\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Dev\Cosmos-master\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
     
	 
     1>Project "C:\Dev\Cosmos-master\source\Build.sln" (1) is building "C:\Dev\Cosmos-master\source\Cosmos.VS.Package\Cosmos.VS.Package.csproj" (18) on node 4 (default targets).
    18>ResolveAssemblyReferences:
         Primary reference "microsoft.VisualStudio.CommonIDE, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL".
    18>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "microsoft.VisualStudio.CommonIDE, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Dev\Cosmos-master\source\Cosmos.VS.Package\Cosmos.VS.Package.csproj]
                 

       "C:\Dev\Cosmos-master\source\Build.sln" (Build target) (1) ->
       "C:\Dev\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj" (default target) (3) ->
       (ResolveAssemblyReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data.SQLite, Version=1.0.99.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Dev\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj]

       "C:\Dev\Cosmos-master\source\Build.sln" (Build target) (1) ->
       "C:\Dev\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj" (default target) (24) ->
       (ResolveAssemblyReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Dev\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]

       "C:\Dev\Cosmos-master\source\Build.sln" (Build target) (1) ->
       "C:\Dev\Cosmos-master\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj" (default target) (4) ->
       "C:\Dev\Cosmos-master\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj" (default target) (9) ->
       (ResolveAssemblyReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Dev\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Dev\Cosmos-master\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]

       "C:\Dev\Cosmos-master\source\Build.sln" (Build target) (1) ->
       "C:\Dev\Cosmos-master\source\Cosmos.VS.Package\Cosmos.VS.Package.csproj" (default target) (18) ->
       (ResolveAssemblyReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "microsoft.VisualStudio.CommonIDE, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Dev\Cosmos-master\source\Cosmos.VS.Package\Cosmos.VS.Package.csproj]

    28 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.78

=================
Copying Templates
=================

Change Dir: C:\Dev\Cosmos-master\Build\VSIP
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\CosmosProject (C#).zip
  To: C:\Dev\Cosmos-master\Build\VSIP\CosmosProject (C#).zip
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\CosmosKernel (C#).zip
  To: C:\Dev\Cosmos-master\Build\VSIP\CosmosKernel (C#).zip
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\CosmosProject (F#).zip
  To: C:\Dev\Cosmos-master\Build\VSIP\CosmosProject (F#).zip
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\Cosmos.zip
  To: C:\Dev\Cosmos-master\Build\VSIP\Cosmos.zip
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\CosmosProject (VB).zip
  To: C:\Dev\Cosmos-master\Build\VSIP\CosmosProject (VB).zip
Copy
  From: C:\Dev\Cosmos-master\source\Cosmos.VS.Package\obj\Debug\CosmosKernel (VB).zip
  To: C:\Dev\Cosmos-master\Build\VSIP\CosmosKernel (VB).zip
Copy
  From: C:\Dev\Cosmos-master\source\XSharp.VS\Template\XSharpFileItem.zip
  To: C:\Dev\Cosmos-master\Build\VSIP\XSharpFileItem.zip

==========================
Creating Inno Setup Script
==========================

==============
Creating Setup
==============

Starting: C:\Program Files (x86)\Inno Setup 5\ISCC.exe
  Params: /Q "C:\Dev\Cosmos-master\Setup\Current.iss" /dBuildConfiguration=DevKit /dVsVersion=vs2015

=============
Running Setup
=============

Starting: schtasks.exe
  Params: /run /tn "CosmosSetup"

=====
Error
=====

Application returned exit code. (0x00000001)
   at Cosmos.Build.Installer.Task.Start(String aExe, String aParams, Boolean aWait, Boolean aShowWindow) in C:\Dev\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 112
   at Cosmos.Build.Builder.CosmosTask.RunSetup() in C:\Dev\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 632
   at Cosmos.Build.Builder.CosmosTask.DoRun() in C:\Dev\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 109
   at Cosmos.Build.Installer.Task.Run() in C:\Dev\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 16
`

**Comment by jp2masa** [comment] 2016-09-17 17:30
Are you using the latest devkit?

**Comment by mmcc1** [comment] 2016-09-17 18:10
Yes, I just grabbed the zip from Github a few hours ago.

**Comment by jp2masa** [comment] 2016-09-17 18:12
I had a similar error today and the cause was an error in building a solution. This log doesn't seem to be complete, try searching in your log to see if you find an error inside the Compiling Cosmos section

**Comment by mmcc1** [comment] 2016-09-17 18:18
No errors in that section.

**Comment by jp2masa** [comment] 2016-09-17 18:19
It's really big, are you sure there's no error? Is "Compiling Cosmos" highlighted as red?

**Comment by mmcc1** [comment] 2016-09-17 18:19
I posted the output to PasteBin:

http://pastebin.com/drQwBjYT

**Comment by mmcc1** [comment] 2016-09-17 18:21
No, 'Running Setup' highlights red, after a few seconds it spits out the error message.

**Comment by jp2masa** [comment] 2016-09-17 18:22
I'm almost sure that the setup didn't get generated

**Comment by mmcc1** [comment] 2016-09-17 18:22
Ok. So what is the solution?

**Comment by jp2masa** [comment] 2016-09-17 18:22
Check Setup/Output

**Comment by jp2masa** [comment] 2016-09-17 18:22
Is there any file?

**Comment by mmcc1** [comment] 2016-09-17 18:23
Just CosmosUserKit-106027-vs2015.exe

**Comment by jp2masa** [comment] 2016-09-17 18:24
Run that... I don't know why it doesn't get run automatically by the Cosmos setup

**Comment by mmcc1** [comment] 2016-09-17 18:24
I have the user kit installed already as a separate download.

**Comment by mmcc1** [comment] 2016-09-17 18:26
I'm trying to build the Devkit.

**Comment by jp2masa** [comment] 2016-09-17 18:27
That's the devkit

**Comment by jp2masa** [comment] 2016-09-17 18:27
The name is userkit, because it's not devkit/userkit dependant

**Comment by jp2masa** [comment] 2016-09-17 18:27
So setup name has always userkit...

**Comment by mmcc1** [comment] 2016-09-17 18:29
I noticed that the Devkit request admin rights, but if you are logged in as a standard user it will attempt to install in the admin account.

**Comment by mmcc1** [comment] 2016-09-17 18:30
Ok. So, that installed.  What now?

**Comment by cjhannah** [comment] 2016-09-17 18:31
that's it. if it installed, follow the get started guide

**Comment by jp2masa** [comment] 2016-09-17 18:31
Now you have the most recent code just use it like the userkit

**Comment by mmcc1** [comment] 2016-09-17 18:32
If there a particular .sln to play around with the underlying code?

**Comment by jp2masa** [comment] 2016-09-17 18:33
it's on source/Cosmos.sln

**Comment by jp2masa** [comment] 2016-09-17 18:33
then you compile it again with install-VS2015.bat

**Comment by jp2masa** [comment] 2016-09-17 18:33
or to test it before compiling you can try TestRunner

**Comment by mmcc1** [comment] 2016-09-17 18:35
Cheers, that appears to be working fine.  One last question, if I were seeking to upgrade X# to x64, would tht be the place to start?  How does IL2CPU fit in?

**Comment by jp2masa** [comment] 2016-09-17 18:36
to get x64 X# wouldn't be the best way it is for 32 bit, you would need to do a copy of X# and give it other name and add x64 on Cosmos.Assembler

**Comment by mmcc1** [comment] 2016-09-17 18:38
I saw that when I had a quick look at the code, its basically a translator between C# syntax and NASM.  When it comes to IL2CPU, this is just a similar approach, is it not?  Only it deals with the broader C# syntax.

**Comment by jp2masa** [comment] 2016-09-17 18:47
IL2CPU just converts IL to ASM using Cosmos.Assembler through X#

**Comment by mmcc1** [comment] 2016-09-17 18:49
That's a great approach, it simplifies everything.  I'll play about with X# and see if I can implement a x64 version.

**Comment by jp2masa** [comment] 2016-09-17 18:50
Start by implementing x64 registers in a copy of X#, with other name, and CPU instructions in Cosmos.Assembler

**Comment by mmcc1** [comment] 2016-09-17 18:52
Ok.  I'll let you know how I get on.

**Comment by mmcc1** [comment] 2016-09-17 19:30
Do you have any examples of X# programs that can be compiled by XSC.exe?

**Comment by jp2masa** [comment] 2016-09-17 19:31
see Cosmos.Debug.DebugStub

**Comment by jp2masa** [comment] 2016-09-17 19:32
but you currently can't use X# files for many things...

**Comment by czhower** [comment] 2016-09-17 19:32
XSC is used by Cosmos to build parts of the kernel. Right now mostly the 
debugstub but will be expanded in the future to handle asm plugs as well.

**Comment by czhower** [comment] 2016-09-17 19:34
X# could be used more. But its by design that its not. We want mostly C# code, and only X# where we cannot use C#... ie Ring 0, DebugStub, etc. The more X# code, the harder it is to port to ARM etc.

**Comment by mmcc1** [comment] 2016-09-17 20:13
I've got a copy now in a separate project and it seems to be working fine.  I switched XSC to GenerateToFiles to examine the output and it seems quite good.  Does it have 16 bit support?  I've written bootloaders before and it would be nice to at least attempt one completely in X#.

**Comment by mmcc1** [comment] 2016-09-17 20:15
Will X# cover all forms of assembly?  Will it be extended to ARM and other processors, allowing IL2CPU to compile down to any architecture?

**Comment by jp2masa** [comment] 2016-09-17 20:16
for arm it will probably be A#

**Comment by jp2masa** [comment] 2016-09-17 20:16
x86 and x64 both start with X so I don't know what will be better to use for x64

**Comment by mmcc1** [comment] 2016-09-17 20:17
Why not create a super language that covers all forms of assembly?  Just keep expanding X#.

**Comment by jp2masa** [comment] 2016-09-17 20:18
I don't know better ask @mterwoord @charlesbetros or @czhower

**Comment by jp2masa** [comment] 2016-09-17 20:19
Also, if you want to discuss Cosmos, join the gitter chat

**Comment by lexected** [comment] 2016-09-17 22:19
Yeah, hey, guys, this is email, not IM. Everytime one of you gets 
involved in a conversation here we receive a generous spam of 60 
one-line emails that make no sense at all.

It's no longer fun.

Please stop.

Dňa 9/17/2016 o 10:19 PM jp2masa napísal(a):

**Comment by fanoI** [comment] 2016-09-19 08:45
As the original issue has been resolved I'll close this now.

**Closed by fanoI** 2016-09-19 08:45 UTC
