### ISSUE TITLE
GUI - Wierd error

### ISSUE THREAD

**Issue by DeadPro60** [CosmosOS/Cosmos#334] opened 2016-02-14 21:52 UTC
When i do display.init() i get these white lines and a few other different pixels. Next, pixel by pixel they disapear. Help?

**Comment by jesus123123** [comment] 2016-02-15 03:05
Yeah, im getting this too. Hellp!!

**Comment by jesus123123** [comment] 2016-02-17 23:26
Oh, i figured this out.

All you have to do is wait for a little bit, and then the graphics will begin. Assuming you have pixels set, what will happen is that when they slowly disappear it will go down the screen, even if there are no pixels, and when its cleared, begin to display the setpixels.

If this helped, please close the issue

**Comment by DeadPro60** [comment] 2016-02-18 03:44
I'll try it brb

**Comment by DeadPro60** [comment] 2016-02-18 03:55
Thanks, jesus123123. When it's done it does set the pixel except, it does'nt continue with the code for example, if i did
'Console.WriteLine("Hello!");'
right after the line, it doesn't display. Help? or is this only for a new post?

**Comment by mterwoord** [comment] 2016-02-18 07:16
After initializing VGA, Console.WriteLine doesn't work anymore I think. That's something that still needs implementing...

**Comment by DeadPro60** [comment] 2016-02-21 02:12
OK! Do i close this issue or leave it?

**Comment by mterwoord** [comment] 2016-02-21 10:10
If the issue is solved, please close it.

**Comment by jesus123123** [comment] 2016-02-23 23:09
The issue is NOT closed. Either close the issue or continue explaining your problem.

You seriously can't keep this open until thats implemented.

**Comment by charlesbetros** [comment] 2016-02-24 01:43
The vga driver should have alternative methods to write text. Use those instead of Console

**Comment by DeadPro60** [comment] 2016-02-24 03:17
charlesbetros how?

**Comment by charlesbetros** [comment] 2016-02-24 05:19
Come find us in Gitter. There is usually someone around most of the day and night. If not ask questions and you'll get a response pretty quickly.

**Closed** 2016-03-02 22:53 UTC
