### ISSUE TITLE
 "error: invalid arch-independent ELF magic" and "error: you need to load the kernel first" While Booting On UEFI BIOS System

### ISSUE THREAD

**Issue by DarkOutcast6** [CosmosOS/Cosmos#2873] opened 2024-01-02 01:18 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
While booting my Cosmos OS ISO file onto my MacBook (running on UEFI BIOS System) using release configuration and VMWARE.

#### Expected Behaviour - What do you think that should happen?
I am able to successfully boot my OS.

#### Actual Behaviour - What unexpectedly happens?
It is stuck in a loop saying "error: invalid arch-independent ELF magic" and "error: you need to load the kernel first" while trying to boot the OS from the GRUB menu.

#### Reproduction - How did you get this error to appear?
Build the ISO file using VMWARE setting on the release configuration (not debug!)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit in C#

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:21
Then your macbook doesnt support x86, it as easy as that. Not a bug.

**Comment by DarkOutcast6** [comment] 2024-01-02 01:27
Ha, good point. It’s a MacBook Pro 2012. Know any way to check if it supports x86?

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:28
yeah thats odd those are intel based so they should support x86 unless they are locked down to like x86_64

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:29
you could try installing the devkit since it uses limine instead of grub, maybe that works

**Comment by DarkOutcast6** [comment] 2024-01-02 01:30
Got it. What is the difference between x86_64 and x86 in this situation, then?

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:32
> Got it. What is the difference between x86_64 and x86 in this situation, then?

well, they are essentially the same but x86_64 is newer and obviously has some changes, but you should usually be able to run an x86 OS regardless.

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:32
> EDIT: How can I port my Userkit program to devkit, then?

Well you just need to install the devkit, thats about it. There arent a ton of breaking changes but you might have to adjust your code a bit

**Comment by DarkOutcast6** [comment] 2024-01-02 01:37
After I install the devkit, in what way might I change my code to work? Is there any differences for actually building an ISO image and booting it on a UEFI BIOS?
___

By the way, this is my current code:
```c#
using System;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {

        protected override void BeforeRun()
        {
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine(" ~ Welcome to Telehack OS! ~ ");
            Console.Write("It is " + DateTime.Now.ToString("h:mm tt") + " on " + DateTime.Now.ToString("M/d/yyyy") + ".");
            Console.WriteLine(@"
 _____________________
| list time info calc | 
| clear date restart  |
| shutdown pi         |
|_____________________|");
            /*Console.ReadKey();*/
        }

        protected override void Run()
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("\n> ");
            var input = Console.ReadLine();
            if (input == "list")
            {
                Console.WriteLine(@"
 _____________________
| list time info calc | 
| clear date restart  |
| shutdown pi         |
|_____________________|");
            }
            else if (input == "help")
            {
                Console.WriteLine(@"Enter a command to learn what it does: ");
                var command = Console.ReadLine();
                if (command == "list")
                {
                    Console.WriteLine("Shows all of the commands.");
                }
                else if (command == "time")
                {
                    Console.WriteLine($"{command} - Shows the current time.");
                }
                else if (command == "info")
                {
                    Console.WriteLine($"{command} - Shows device info.");
                }
                else if (command == "calc")
                {
                    Console.WriteLine($"{command} - A basic caculator.");
                }
                else if (command == "clear")
                {
                    Console.WriteLine($"{command} - Clears the command line.");
                }
                else if (command == "date")
                {
                    Console.WriteLine($"{command} - Shows the current date.");
                }
                else if (command == "restart" || command == "reboot")
                {
                    Console.WriteLine($"{command} - Restarts the machine.");
                }
                else if (command == "shutdown" || command == "shut down")
                {
                    Console.WriteLine($"{command} - Restarts the machine.");
                }
                else if (command == "pi")
                {
                    Console.WriteLine($"{command} - Recites 50 trillion digits of pi (.");
                }
                else
                {
                    Console.WriteLine("No command with the name of \"" + command + "\"!");
                }
            }
            else if (input == "time")
            {
                Console.WriteLine(DateTime.Now.ToString("h:mm:ss tt"));
            }
            else if (input == "clear")
            {
                Console.Clear();
            }
            else if (input == "date")
            {
                Console.WriteLine(DateTime.Now.ToString("M/d/yyyy"));
            }
            else if (input == "info")
            {
                Console.WriteLine($"Manufacturer: N/A");
                Console.WriteLine($"Model: N/A");
                Console.WriteLine($"Storage Total: N/A");
                Console.WriteLine($"Storage Left: N/A");
                Console.WriteLine($"Memory: N/A");
            }
            else if (input == "calc")
            {
                /*var toCalc = Console.ReadLine();
                Console.WriteLine(@toCalc);*/
                string toCalc = "1+1";
                try
                {
                    double equation = Convert.ToDouble(toCalc);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                }
                /*Console.WriteLine($"{equation}");*/
                /*Console.WriteLine($"{toCalc} = {equation}");*/
            }
            else if (input == "shutdown" || input == "shut down")
            {
                Cosmos.System.Power.Shutdown();
            }
            else if (input == "reboot" || input == "restart")
            {
                Cosmos.System.Power.Reboot();
            }
            else if (input == "pi")
            {
                Console.WriteLine("3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268066130019278766111959092164201989380952572010654858632788659361533818279682303019520353018529689957736225994138912497217752834791315155748572424541506959508295331168617278558890750983817546374649393192550604009277016711390098488240128583616035637076601047101819429555961989467678374494482553797747268471040475346462080466842590694912933136770289891521047521620569660240580381501935112533824300355876402474964732639141992726042699227967823547816360093417216412199245863150302861829745557067498385054945885869269956909272107975093029553211653449872027559602364806654991198818347977535663698074265425278625518184175746728909777727938000816470600161452491921732172147723501414419735685481613611573525521334757418494684385233239073941433345477624168625189835694855620992192221842725502542568876717904946016534668049886272327917860857843838279679766814541009538837863609506800642251252051173929848960841284886269456042419652850222106611863067442786220391949450471237137869609563643719172874677646575739624138908658326459958133904780275900994657640789512694683983525957098258226205224894077267194782684826014769909026401363944374553050682034962524517493996514314298091906592509372216964615157098583874105978859597729754989301617539284681382686838689427741559918559252459539594310499725246808459872736446958486538367362226260991246080512438843904512441365497627807977156914359977001296160894416948685558484063534220722258284886481584560285060168427394522674676788952521385225499546667278239864565961163548862305774564980355936345681743241125150760694794510965960940252288797108931456691368672287489405601015033086179286809208747609178249385890097149096759852613655497818931297848216829989487226588048575640142704775551323796414515237462343645428584447952658678210511413547357395231134271661021359695362314429524849371871101457654035902799344037420073105785390621983874478084784896833214457138687519435064302184531910484810053706146806749192781911979399520614196634287544406437451237181921799983910159195618146751426912397489409071864942319615679452080951465502252316038819301420937621378559566389377870830390697920773467221825625996615014215030680384477345492026054146659252014974428507325186660021324340881907104863317346496514539057962685610055081066587969981635747363840525714591028970641401109712062804390397595156771577004203378699360072305587631763594218731251471205329281918261861258673215791984148488291644706095752706957220917567116722910981690915280173506712748583222871835209353965725121083579151369882091444210067510334671103141267111369908658516398315019701651511685171437657618351556508849099898599823873455283316355076479185358932261854896321329330898570642046752590709154814165498594616371802709819943099244889575712828905923233260972997120844335732654893823911932597463667305836041428138830320382490375898524374417029132765618093773444030707469211201913020330380197621101100449293215160842444859637669838952286847831235526582131449576857262433441893039686426243410773226978028073189154411010446823252716201052652272111660396665573092547110557853763466820653109896526918620564769312570586356620185581007293606598764861179104533488503461136576867532494416680396265797877185560845529654126654085306143444318586769751456614068007002378776591344017127494704205622305389945613140711270004078547332699390814546646458807972708266830634328587856983052358089330657574067954571637752542021149557615814002501262285941302164715509792592309907965473761255176567513575178296664547791745011299614890304639947132962107340437518957359614589019389713111790429782856475032031986915140287080859904801094121472213179476477726224142548545403321571853061422881375850430633217518297986622371721591607716692547487389866549494501146540628433663937900397692656721463853067360965712091807638327166416274888800786925602902284721040317211860820419000422966171196377921337575114959501566049631862947265473642523081770367515906735023507283540567040386743513622224771589150495309844489333096340878076932599397805419341447377441842631298608099888687413260472156951623965864573021631598193195167353812974167729478672422924654366800980676928238280689964004824354037014163149658979409243237896907069779422362508221688957383798623001593776471651228935786015881617557829735233446042815126272037343146531977774160319906655418763979293344195215413418994854447345673831624993419131814809277771038638773431772075456545322077709212019051660962804909263601975988281613323166636528619326686336062735676303544776280350450777235547105859548702790814356240145171806246436267945612753181340783303362542327839449753824372058353114771199260638133467768796959703098339130771098704085913374641442822772634659470474587847787201927715280731767907707157213444730605700733492436931138350493163128404251219256517980694113528013147013047816437885185290928545201165839341965621349143415956258658655705526904965209858033850722426482939728584783163057777560688876446248246857926039535277348030480290058760758251047470916439613626760449256274204208320856611906254543372131535958450687724602901618766795240616342522577195429162991930645537799140373404328752628889639958794757291746426357455254079091451357111369410911939325191076020825202618798531887705842972591677813149699009019211697173727847684726860849003377024242916513005005168323364350389517029893922334517220138128069650117844087451960121228599371623130171144484640903890644954440061986907548516026327505298349187407866808818338510228334508504860825039302133219715518430635455007668282949304137765527939751754613953984683393638304746119966538581538420568533862186725233402830871123282789212507712629463229563989898935821167456270102183564622013496715188190973038119800497340723961036854066431939509790190699639552453005450580685501956730229219139339185680344903982059551002263535361920419947455385938102343955449597783779023742161727111723643435439478221818528624085140066604433258885698670543154706965747458550332323342107301545940516553790686627333799585115625784322988273723198987571415957811196358330059408730681216028764962867446047746491599505497374256269010490377819868359381465741268049256487985561453723478673303904688383436346553794986419270563872931748723320837601123029911367938627089438799362016295154133714248928307220126901475466847653576164773794675200490757155527819653621323926406160136358155907422020203187277605277219005561484255518792530343513984425322341576233610642506390497500865627109535919465897514131034822769306247435363256916078154781811528436679570611086153315044521274739245449454236828860613408414863776700961207151249140430272538607648236341433462351897576645216413767969031495019108575984423919862916421939949072362346468441173940326591840443780513338945257423995082965912285085558215725031071257012668302402929525220118726767562204154205161841634847565169998116141010029960783869092916030288400269104140792886215078424516709087000699282120660418371806535567252532567532861291042487761825829765157959847035622262934860034158722980534989650226291748788202734209222245339856264766914905562842503912757710284027998066365825488926488025456610172967026640765590429099456815065265305371829412703369313785178609040708667114965583434347693385781711386455873678123014587687126603489139095620099393610310291616152881384379099042317473363948045759314931405297634757481193567091101377517210080315590248530906692037671922033229094334676851422144773793937517034436619910403375111735471918550464490263655128162288244625759163330391072253837421821408835086573917715096828874782656995995744906617583441375223970968340800535598491754173818839994469748676265516582765848358845314277568790029095170283529716344562129640435231176006651012412006597558512761785838292041974844236080071930457618932349229279650198751872127267507981255470958904556357921221033346697499235630254947802490114195212382815309114079073860251522742995818072471625916685451333123948049470791191532673430282441860414263639548000448002670496248201792896476697583183271314251702969234889627668440323260927524960357996469256504936818360900323809293459588970695365349406034021665443755890045632882250545255640564482465151875471196218443965825337543885690941130315095261793780029741207665147939425902989695946995565761218656196733786236256125216320862869222103274889218654364802296780705765615144632046927906821207388377814233562823608963208068222468012248261177185896381409183903673672220888321513755600372798394004152970028783076670944474560134556417254370906979396122571429894671543578468788614445812314593571984922528471605049221242470141214780573455105008019086996033027634787081081754501193071412233908663938339529425786905076431006383519834389341596131854347546495569781038293097164651438407007073604112373599843452251610507027056235266012764848308407611830130527932054274628654036036745328651057065874882256981579367897669742205750596834408697350201410206723585020072452256326513410559240190274216248439140359989535394590944070469120914093870012645600162374288021092764579310657922955249887275846101264836999892256959688159205600101655256375678566722796619885782794848855834397518744545512965634434803966420557982936804352202770984294232533022576341807039476994159791594530069752148293366555661567873640053666564165473217043903521329543529169414599041608753201868379370234888689479151071637852902345292440773659495630510074210871426134974595615138498713757047101787957310422969066670214498637464595280824369445789772330048764765241339075920434019634039114732023380715095222010682563427471646024335440051521266932493419673977041595683753555166730273900749729736354964533288869844061196496162773449518273695588220757355176651589855190986665393549481068873206859907540792342402300925900701731960362254756478940647548346647760411463233905651343306844953979070903023460461470961696886885014083470405460742958699138296682468185710318879065287036650832431974404771855678934823089431068287027228097362480939962706074726455399253994428081137369433887294063079261595995462624629707062594845569034711972996409089418059534393251236235508134949004364278527138315912568989295196427287573946914272534366941532361004537304881985517065941217352462589548730167600298865925786628561249665523533829428785425340483083307016537228563559152534784459818313411290019992059813522051173365856407826484942764411376393866924803118364453698589175442647399882284621844900877769776312795722672655562596282542765318300134070922334365779160128093179401718598599933849235495640057099558561134980252499066984233017350358044081168552653117099570899427328709258487894436460050410892266917835258707859512983441729535195378855345737426085902908176515578039059464087350612322611200937310804854852635722825768203416050484662775045003126200800799804925485346941469775164932709504934639382432227188515974054702148289711177792376122578873477188196825462981268685817050740272550263329044976277894423621674119186269439650671515779586756482399391760426017633870454990176143641204692182370764887834196896861181558158736062938603810171215855272668300823834046564758804051380801633638874216371406435495561868964112282140753302655100424104896783528588290243670904887118190909494533144218287661810310073547705498159680772009474696134360928614849417850171807793068108546900094458995279424398139213505586422196483491512639012803832001097738680662877923971801461343244572640097374257007359210031541508936793008169980536520276007277496745840028362405346037263416554259027601834840306811381855105979705664007509426087885735796037324514146786703688098806097164258497595138069309449401515422221943291302173912538355915031003330325111749156969174502714943315155885403922164097229101129035521815762823283182342548326111912800928252561902052630163911477247331485739107775874425387611746578671169414776421441111263583553871361011023267987756410246824032264834641766369806637857681349204530224081972785647198396308781543221166912246415911776732253264335686146186545222681268872684459684424161078540167681420808850280054143613146230821025941737562389942075713627516745731891894562835257044133543758575342698699472547031656613991999682628247270641336222178923903176085428943733935618891651250424404008952719837873864805847268954624388234375178852014395600571048119498842390606136957342315590796703461491434478863604103182350736502778590897578272731305048893989009923913503373250855982655867089242612429473670193907727130706869170926462548423240748550366080136046689511840093668609546325002145852930950000907151058236267293264537382104938724996699339424685516483261134146110680267446637334375340764294026682973865220935701626384648528514903629320199199688285171839536691345222444708045923966028171565515656661113598231122506289058549145097157553900243931535190902107119457300243880176615035270862602537881797519478061013715004489917210022201335013106016391541589578037117792775225978742891917915522417189585361680594741234193398420218745649256443462392531953135103311476394911995072858430658361935369329699289837914941939406085724863968836903265564364216644257607914710869984315733749648835292769328220762947282381537409961545598798259891093717126218283025848112389011968221429457667580718653806506487026133892822994972574530332838963818439447707794022843598834100358385423897354243956475556840952248445541392394100016207693636846776413017819659379971557468541946334893748439129742391433659360410035234377706588867781139498616478747140793263858738624732889645643598774667638479466504074111825658378878454858148962961273998413442726086061872455452360643153710112746809778704464094758280348769758948328241239292960582948619196670918958089833201210318430340128495116203534280144127617285830243559830032042024512072872535581195840149180969253395075778400067465526031446167050827682772223534191102634163157147406123850425845988419907611287258059113935689601431668283176323567325417073420817332230462987992804908514094790368878687894930546955703072619009502076433493359106024545086453628935456862958531315337183868265617862273637169757741830239860065914816164049449650117321313895747062088474802365371031150898427992754426853277974311395143574172219759799359685252285745263796289612691572357986620573408375766873884266405990993505000813375432454635967504844235284874701443545419576258473564216198134073468541117668831186544893776979566517279662326714810338643913751865946730024434500544995399742372328712494834706044063471606325830649829795510109541836235030309453097335834462839476304775645015008507578949548931393944899216125525597701436858943585877526379625597081677643800125436502371412783467926101995585224717220177723700417808419423948725406801556035998390548985723546745642390585850216719031395262944554391316631345308939062046784387785054239390524731362012947691874975191011472315289326772533918146607300089027768963114810902209724520759167297007850580717186381054967973100167870850694207092232908070383263453452038027860990556900134137182368370991949516489600755049341267876436746384902063964019766685592335654639138363185745698147196210841080961884605456039038455343729141446513474940784884423772175154334260306698831768331001133108690421939031080143784334151370924353013677631084913516156422698475074303297167469640666531527035325467112667522460551199581831963763707617991919203579582007595605302346267757943936307463056901080114942714100939136913810725813781357894005599500183542511841721360557275221035268037357265279224173736057511278872181908449006178013889710770822931002797665935838758909395688148560263224393726562472776037890814458837855019702843779362407825052704875816470324581290878395232453237896029841669225489649715606981192186584926770403956481278102179913217416305810554598801300484562997651121241536374515005635070127815926714241342103301566165356024733807843028655257222753049998837015348793008062601809623815161366903341111386538510919367393835229345888322550887064507539473952043968079067086806445096986548801682874343786126453815834280753061845485903798217994599681154419742536344399602902510015888272164745006820704193761584547123183460072629339550548239557137256840232268213012476794522644820910235647752723082081063518899152692889108455571126603965034397896278250016110153235160519655904211844949907789992007329476905868577878720982901352956613978884860509786085957017731298155314951681467176959760994210036183559138777817698458758104466283998806006162298486169353373865787735983361613384133853684211978938900185295691967804554482858483701170967212535338758621582310133103877668272115726949518179589754693992642197915523385766231676275475703546994148929041301863861194391962838870543677743224276809132365449485366768000001065262485473055861598999140170769838548318875014293890899506854530765116803337322265175662207526951791442252808165171667766727930354851542040238174608923283917032754257508676551178593950027933895920576682789677644531840404185540104351348389531201326378369283580827193783126549617459970567450718332065034556644034490453627560011250184335607361222765949278393706478426456763388188075656121689605041611390390639601620221536849410926053876887148379895599991120991646464411918568277004574243434021672276445589330127781586869525069499364610175685060167145354315814801054588605645501332037586454858403240298717093480910556211671546848477803944756979804263180991756422809873998766973237695737015808068229045992123661689025962730430679316531149401764737693873514093361833216142802149763399189835484875625298752423873077559555955465196394401821840998412489826236737714672260616336432964063357281070788758164043814850188411431885988276944901193212968271588841338694346828590066640806314077757725705630729400492940302420498416565479736705485580445865720227637840466823379852827105784319753541795011347273625774080213476826045022851579795797647467022840999561601569108903845824502679265942055503958792298185264800706837650418365620945554346135134152570065974881916341359556719649654032187271602648593049039787489589066127250794828276938953521753621850796297785146188432719223223810158744450528665238022532843891375273845892384422535472653098171578447834215822327020690287232330053862163479885094695472004795231120150432932266282727632177908840087861480221475376578105819702226309717495072127248479478169572961423658595782090830733233560348465318730293026659645013718375428897557971449924654038681799213893469244741985097334626793321072686870768062639919361965044099542167627840914669856925715074315740793805323925239477557441591845821562518192155233709607483329234921034514626437449805596103307994145347784574699992128599999399612281615219314888769388022281083001986016549416542616968586788372609587745676182507275992950893180521872924610867639958916145855058397274209809097817293239301067663868240401113040247007350857828724627134946368531815469690466968693925472519413992914652423857762550047485295476814795467007050347999588867695016124972282040303995463278830695976249361510102436555352230690612949388599015734661023712235478911292547696176005047974928060721268039226911027772261025441492215765045081206771735712027180242968106203776578837166909109418074487814049075517820385653909910477594141321543284406250301802757169650820964273484146957263978842560084531214065935809041271135920041975985136254796160632288736181367373244506079244117639975974619383584574915988097667447093006546342423460634237474666080431701260052055928493695941434081468529815053947178900451835755154125223590590687264878635752541911288877371766374860276606349603536794702692322971868327717393236192007774522126247518698334951510198642698878471719396649769070825217423365662725928440620430214113719922785269984698847702323823840055655517889087661360130477098438611687052310553149162517283732728676007248172987637569816335415074608838663640693470437206688651275688266149730788657015685016918647488541679154596507234287730699853713904300266530783987763850323818215535597323530686043010675760838908627049841888595138091030423595782495143988590113185835840667472370297149785084145853085781339156270760356390763947311455495832266945702494139831634332378975955680856836297253867913275055542524491943589128405045226953812179131914513500993846311774017971512283785460116035955402864405902496466930707769055481028850208085800878115773817191741776017330738554758006056014337743299012728677253043182519757916792969965041460706645712588834697979642931622965520168797300035646304579308840327480771811555330909887025505207680463034608658165394876951960044084820659673794731680864156456505300498816164905788311543454850526600698230931577765003780704661264706021457505793270962047825615247145918965223608396645624105195510522357239739512881816405978591427914816542632892004281609136937773722299983327082082969955737727375667615527113922588055201898876201141680054687365580633471603734291703907986396522961312801782679717289822936070288069087768660593252746378405397691848082041021944719713869256084162451123980620113184541244782050110798760717155683154078865439041210873032402010685341947230476666721749869868547076781205124736792479193150856444775379853799732234456122785843296846647513336573692387201464723679427");
            }
            else
            {
                if (!(input == ""))
                {
                    Console.WriteLine("No command with the name of \"" + input + "\"");
                }
            }
        }

    }
}
```

**Comment by GoldenretriverYT** [comment] 2024-01-02 01:45
unless you are getting errors everything is fine, there were some breaking changes but prob nothing that affected you. building the iso should be the same

**Comment by DarkOutcast6** [comment] 2024-01-02 01:46
Got it. Where is the DevKit installation located? I couldn't find it on the COSMOS webpage.

**Comment by zarlo** [comment] 2024-01-02 01:57
> @GoldenretriverYT Got it. Where is the DevKit installation located? I couldn't find it on the COSMOS webpage.

same as userkit

"%appdata%/local/Cosmo User Kit" (i think) on windows
/opt/cosmos on linux

**Comment by DarkOutcast6** [comment] 2024-01-02 02:11
@zarlo But how do I _install_ the devkit?

**Comment by zarlo** [comment] 2024-01-02 02:19
> @zarlo But how do I _install_ the devkit?

oh https://cosmosos.github.io/install.html#dev-kit

* install git 
* install Workload: Visual Studio Extension Development
* Inno Setup (Free) – Install with defaults
* clone the main repo https://github.com/cosmosos/cosmos.git
* run install-VS2022.bat

**Comment by DarkOutcast6** [comment] 2024-01-02 02:35
I believe I have done so. What do I do next?

**Comment by zarlo** [comment] 2024-01-02 02:40
run install-VS2022.bat

**Comment by DarkOutcast6** [comment] 2024-01-02 02:42
@zarlo Does that install Visual Studio? If so, I already have Visual Studio 2022 from when I installed the UserKit.

**Comment by zarlo** [comment] 2024-01-02 02:44
> @zarlo Does that install Visual Studio? If so, I already have Visual Studio 2022 from when I installed the UserKit.

no i does not i just has VS2022 in its name as there was a time when VS2019 and VS2022 where supported at the same time

**Comment by DarkOutcast6** [comment] 2024-01-02 02:45
@zarlo I don’t understand… what does `iinstall-VS2022.bat` do?

**Comment by zarlo** [comment] 2024-01-02 02:52
it installs cosmos

**Comment by DarkOutcast6** [comment] 2024-01-02 02:57
@zarlo Where is it located on my computer?

**Comment by zarlo** [comment] 2024-01-02 03:00
> @zarlo Where is it located on my computer?

its in the cosmos repo so where ever you cloned to repo

**Comment by DarkOutcast6** [comment] 2024-01-02 03:09
@zarlo Found it. For some reason, when I run it (even if I run it as administrator) it opens, then it briefly blinks a paragraph in red text that may be an error, but it quickly closes the console, so I am unable to read it. I will try to freeze the screen to get a closer look.

**Comment by zarlo** [comment] 2024-01-02 03:12
open powershell and run it from there

**Comment by DarkOutcast6** [comment] 2024-01-02 03:22
Here's the error:
```
D:\amfut\Documents\COSMOS_OS\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error : Could not resolve SDK "M
icrosoft.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate an
d resolve that message to correctly specify the SDK.
D:\amfut\Documents\COSMOS_OS\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error :   The NuGetSdkResolver d
id not resolve this SDK because there was no version specified in the project or global.json.
D:\amfut\Documents\COSMOS_OS\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error :   MSB4276: The default S
DK resolver failed to resolve SDK "Microsoft.NET.Sdk" because directory "C:\Program Files\Microsoft Visual Studio\2022\
Community\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk" did not exist.
D:\amfut\Documents\COSMOS_OS\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error MSB4236: The SDK 'Microsof
t.NET.Sdk' specified could not be found.
```
looks like something to do with the .NET SDK, but I thought I installed it... maybe not?

**Comment by zarlo** [comment] 2024-01-02 03:25
do you have net6.0 installed?

**Comment by DarkOutcast6** [comment] 2024-01-02 03:29
I thought I did… when I installed it from .NET 6.0.25 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0, I seem to remember it successfully installing. Should I try to install it again or am I doing something wrong?

**Comment by DarkOutcast6** [comment] 2024-01-02 03:45
@zarlo Just tested, looks like I have .NET6 installed on my computer. I tried reinstalling it, but it did nothing. Is it possible that COSMOS may simply just not have the path to the .NET installation? If so, how could I fix that? If not, what do you think it is?

**Comment by zarlo** [comment] 2024-01-02 03:49
i think you might need .net 4.8 too on windows

**Comment by DarkOutcast6** [comment] 2024-01-02 03:53
@zarlo Hmm… okay, I’ll try to install it.

**Comment by DarkOutcast6** [comment] 2024-01-02 03:57
@zarlo Just installed 4.8, didn’t do anything. What else might I need to do?

**Comment by DarkOutcast6** [comment] 2024-01-02 15:40
@zarlo Just got rid of the error! Had to install the .NET development workload, and everything seems to be working well. Now, how do I switch my CosmosKernel to use DevKit instead of UserKit? Will it automatically do so, or do I have to uninstall UserKit or something?

**Comment by quajak** [comment] 2024-01-02 20:17
Seems to be a duplicate of https://github.com/CosmosOS/Cosmos/issues/2773. Please open new issues if you have new questions. If you need help using Cosmos please use the discussions or the discord rather than issues.

**Closed by quajak** 2024-01-02 20:17 UTC
Labels: Bug

**Comment by DarkOutcast6** [comment] 2024-01-02 21:11
After a bit more research, I was able to mess around with configuration and the `.csproj` and figure everything out (at least for now 😲 ). Thank you so much for the help @zarlo and @GoldenretriverYT!
