### ISSUE TITLE
Build fail on windows 11 after .NET 5.0 update (Unoffical 4.x works, All deps including .NET 5.0 is installed.)

### ISSUE THREAD

**Issue by Malte0621** [CosmosOS/Cosmos#2012] opened 2021-11-19 15:49 UTC
Have you checked Github Issues for similar errors? Yes

**Exception**
```
The process failed to execute!
Error: 
CSC : error CS1705: Assembly 'IL2CPU.Debug.Symbols' with identity 'IL2CPU.Debug.Symbols, Version=10.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
```

**VS Output Logs**
https://pastebin.com/raw/2j3xvHQX

**To Reproduce**
Attempt to build the project using `install-VS2019.bat` on windows 11, with .NET 5.0 and all deps installed.
(All repos cloned, everything setup as told)

**Screenshots**
![image](https://user-images.githubusercontent.com/50240920/142649586-0c4a7d6b-28e1-4293-84b4-0ee353bbaa2c.png)

**Context**
Before posting please confirm that the following are in order
[ x ] Both Cosmos VS Extensions are installed
[ x ] In the NuGet Package Manager "Include prerelease" is selected
[ x ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ x ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
Only occuress after .NET 5.0 upgrade, unofficial 4.x ones I used compiles without problem. (I have .NET 5.0 SDK and Runtime installed.) I am however on windows 11.

Unoffical Ones I used: https://github.com/xccoreco

**Comment by valentinbreiz** [comment] 2021-11-19 15:53
Duplicate of https://github.com/CosmosOS/Cosmos/issues/1962

@quajak any idea?

**Comment by KM198912** [comment] 2021-11-19 18:53
restart the install bat with admin permissions

**Comment by Malte0621** [comment] 2021-11-19 21:40
Alr, Ima try to run with admin.

**Comment by quajak** [comment] 2021-11-19 21:41
Can you please run `msbuild -restore Build.sln /bl` from a devenv console and upload the created log file and report any errors thrown. Then please repeat the process for `msbuild -restore Build.sln /bl /property:Net48=True`.

**Comment by Malte0621** [comment] 2021-11-19 22:21
After running the first command from @quajak I got this:
```
"C:\Users\Malte0621\Downloads\build\Cosmos\Build.sln" (default target) (1:2) ->
"C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj" (default targ
et) (3:6) ->
(FindExistingDeploymentPath target) ->
  C:\Users\Malte0621\.nuget\packages\microsoft.vssdk.buildtools\16.8.3038\tools\VSSDK\Microsoft.VsSDK.targets(812,5): e
rror : Extension 'Cosmos.VS.ProjectSystem' is of the same or lower version than the installed extension. Please make su
re that the extension version is higher than that of the installed extension. [C:\Users\Malte0621\Downloads\build\Cosmo
s\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]

    99 Warning(s)
    1 Error(s)

Time Elapsed 00:00:29.04
``` (I can't copy the full thing, Its HUGE.)

Running second one now..

**Comment by Malte0621** [comment] 2021-11-19 22:23
After running second one.

```
"C:\Users\Malte0621\Downloads\build\Cosmos\Build.sln" (default target) (1:2) ->
"C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj" (default targ
et) (3:6) ->
(FindExistingDeploymentPath target) ->
  C:\Users\Malte0621\.nuget\packages\microsoft.vssdk.buildtools\16.8.3038\tools\VSSDK\Microsoft.VsSDK.targets(812,5): e
rror : Extension 'Cosmos.VS.ProjectSystem' is of the same or lower version than the installed extension. Please make su
re that the extension version is higher than that of the installed extension. [C:\Users\Malte0621\Downloads\build\Cosmo
s\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]

    39 Warning(s)
    1 Error(s)

Time Elapsed 00:00:13.60
```

**Comment by Malte0621** [comment] 2021-11-19 22:27
After installing a few times with admin permission, I get:
```
========================================
    Error
========================================

Collection was modified; enumeration operation may not execute.
```
and
```
========================================
    Error
========================================

The process failed to execute!
Error: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Malte0621\Downloads\build\Cosmos\Build\VSIP\System.Security.Cryptography.Csp.dll". [C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
```
and sometimes:
```
========================================
    Error
========================================

The process failed to execute!
Error: 
CSC : error CS1705: Assembly 'IL2CPU.Debug.Symbols' with identity 'IL2CPU.Debug.Symbols, Version=10.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
```

**Comment by quajak** [comment] 2021-11-19 22:30
> After running the first command from @quajak I got this:
> 
> ```
> "C:\Users\Malte0621\Downloads\build\Cosmos\Build.sln" (default target) (1:2) ->
> "C:\Users\Malte0621\Downloads\build\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj" (default targ
> et) (3:6) ->
> (FindExistingDeploymentPath target) ->
>   C:\Users\Malte0621\.nuget\packages\microsoft.vssdk.buildtools\16.8.3038\tools\VSSDK\Microsoft.VsSDK.targets(812,5): e
> rror : Extension 'Cosmos.VS.ProjectSystem' is of the same or lower version than the installed extension. Please make su
> re that the extension version is higher than that of the installed extension. [C:\Users\Malte0621\Downloads\build\Cosmo
> s\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
> 
>     99 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:29.04
> ```
> 
> (can't copy the full thing, Its HUGE.)
> 
> Running second one now..

This means that you arnt on the newest devkit state, where the problem should be fixed.

**Comment by TaromaruYuki** [comment] 2021-11-25 05:41
> Can you please run `msbuild -restore Build.sln /bl` from a devenv console and upload the created log file and report any errors thrown. Then please repeat the process for `msbuild -restore Build.sln /bl /property:Net48=True`.

This does work, for me at least. Running the two commands, not as admin, then opening `install-VS2019.bat` as admin. Even if errors are listed in the two commands. Cloned the 4 repo's today.

I am on Windows 11, version 21H2, build 22000.318. 👍

**Closed** 2022-03-11 13:28 UTC
Labels: Priority: High, Area: Visual Studio Integration, Area: Build
