### ISSUE TITLE
Grub error: ELF sections outside of core

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2130] opened 2022-02-19 20:29 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
Runtime (in vbox, related to grub.)

#### Expected Behaviour - What do you think that should happen?
the cosmos kernel should begin to load

#### Actual Behaviour - What unexpectedly happens?
grub has an error and drops into the grub recovery shell

#### Reproduction - How did you get this error to appear?
Compile the code from https://www.github.com/project-prism/prism-os/ using the latest version of cosmos devkit

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit
all from latest repos

#### Screenshot
![VirtualBox_Prism_19_02_2022_11_21_57](https://user-images.githubusercontent.com/76945439/154818022-d4ea52bf-0f75-42f2-a899-68c60ae6e497.png)

**Comment by quajak** [comment] 2022-02-21 18:05
@valentinbreiz Any ideas what the cause could be?

**Comment by valentinbreiz** [comment] 2022-02-21 18:54
Boots fine on bochs and VMWare :/

VirtualBox is not working for me I can't test

![image](https://user-images.githubusercontent.com/18724279/155012014-60b8852f-291c-48db-8268-fed4b5a62acb.png)

![image](https://user-images.githubusercontent.com/18724279/155012311-06d69e70-803c-4cf2-a8dc-6ea50d04b523.png)

@terminal-cs, could you try this ISO and tell me if your problem still happens? https://anonfiles.com/R4c10aJ0x6/PrismOS_iso

**Comment by terminal-cs** [comment] 2022-02-22 01:53
> Boots fine on bochs and VMWare using last commits :/
> 
> VirtualBox is not working for me due to WSL2 I can't test on this VM
> 
> ![image](https://user-images.githubusercontent.com/18724279/155012014-60b8852f-291c-48db-8268-fed4b5a62acb.png)
> 
> ![image](https://user-images.githubusercontent.com/18724279/155012311-06d69e70-803c-4cf2-a8dc-6ea50d04b523.png)
> 
> @terminal-cs, could you try this ISO and tell me if your problem still happens? https://anonfiles.com/R4c10aJ0x6/PrismOS_iso

That iso works for me
btw, I'm rewriting the thing I am doing so perhaps it will work better this time

**Comment by valentinbreiz** [comment] 2022-02-22 02:00
Okay, I suggest you to reinstall Cosmos and rebuild
I close this

**Closed by valentinbreiz** 2022-02-22 02:00 UTC
Labels: Bug, Pending User Response, Area: Bootloader
