### ISSUE TITLE
Console.ReadKey() doesn't like certain keys.

### ISSUE THREAD

**Issue by MichaelTheShifter** [CosmosOS/Cosmos#387] opened 2016-06-18 10:52 UTC
So I converted all my OS to use ReadKey() for single-key input. I tested it. Keys like Enter, Esc, all number keys at the top of the keyboard, and all alphabetic keys work fine. Shift works fine, and makes keys that can become 'uppercase' become 'uppercase'. However, the following keys throw the following "KeyEx not yet implemented" error. Note that all keys in the list that I've tested do the same in their lowercase and uppercase variants on a US keyboard layout.
- \
- /
- (dash, omitted because markdown)
- .
- ,
- ]
- [
- {
- }
- =
- ;
- '

These keys should be fixed - because, what if someone uses ReadKey() to receive input for a multiline input, and they want to write a simple sentence, i.e, "I'm typing words with my hands.", they can't. The OS will halt the text editor (like Memphis does if an app throws an exception - it'll halt the loop and return to the command line) or even crash the OS.

Not sure if keys like 'Tab' or numeric keypad buttons work - I don't use them. I know the Arrow Keys work fine as they're used to navigate menus in Memphis.

**Comment by MichaelTheShifter** [comment] 2016-06-18 20:09
Closing because I fixed it myself.

**Comment by mterwoord** [comment] 2016-06-18 20:12
The issue is solved when the PR gets merged..

**Comment by jp2masa** [comment] 2016-11-30 19:07
This issue should have been closed when the PR was merged, closing it now.

**Closed by jp2masa** 2016-11-30 19:07 UTC
