### ISSUE TITLE
Devkit Installation - Nuget certificate error

### ISSUE THREAD

**Issue by asterd-og** [CosmosOS/Cosmos#1793] opened 2021-05-29 00:43 UTC
**Description**
Sooo, i am trying to install devkit on my computer, (devkit 2020), and some errors appears

**Errors**
![image](https://user-images.githubusercontent.com/73673156/120052873-dbc9d200-bffd-11eb-9325-68a8726238dd.png)
(the error is in pt-BR)

**Setup**
 - Cosmos Version = 20200708
 - Are you using an admin account? = yes
 - VS Version if applicable = last

**Additional context**
the devkit fails in any version of cosmos/vs that i try

**Comment by quajak** [comment] 2021-05-29 08:16
I can't read the language, but from the errors in the console I would assume that it cant connect to `https://api.nuget.org/v3/index.json`. Is that correct? Otherwise please translate the error messages.

**Comment by asterd-og** [comment] 2021-05-29 17:27
> I can't read the language, but from the errors in the console I would assume that it cant connect to `https://api.nuget.org/v3/index.json`. Is that correct? Otherwise please translate the error messages.

yes correct

**Comment by AnErrupTion** [comment] 2021-05-29 20:55
It seems like it's a certificate error. This could be due to Windows 7, but I have no idea.

**Comment by asterd-og** [comment] 2021-05-29 22:47
> It seems like it's a certificate error. This could be due to Windows 7, but I have no idea.

yeah, the other erros is talking about the certification error, but... idk how to solve that...
also, sorry about my bad english, i'm brazilian

**Comment by AnErrupTion** [comment] 2021-05-30 07:27
Did you do all Windows 7 updates? (Just to be sure it's not a missing update problem)

**Comment by quajak** [comment] 2021-05-30 07:49
This seems like a problem with your local nuget configuration. Your best bet would be google since the cause of this error is not cosmos itself and its very difficult to diagnose from afar.

**Comment by asterd-og** [comment] 2021-05-30 21:41
> Did you do all Windows 7 updates? (Just to be sure it's not a missing update problem)

yeah

**Comment by asterd-og** [comment] 2021-05-30 21:42
> This seems like a problem with your local nuget configuration. Your best bet would be google since the cause of this error is not cosmos itself and its very difficult to diagnose from afar.

i already searched a lot, but i can't find anything...

**Comment by Arawn-Davies** [comment] 2021-06-11 11:37
Windows 7 isn't supported by Microsoft anymore, and .NET 5 (which Cosmos will be targeting in the near future) won't be supporting Windows 7 either, so we highly recommend you updating to WIndows 10. (I don't think any of us on the Cosmos Core Team actually use Windows 7 anymore...)


 A potential fix for this issue is to enable Extended Security Updates for Windows 7, but if you're unable to, it's not worth spending any more time looking into this issue.
 https://docs.microsoft.com/en-gb/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq

**Closed** 2021-06-11 11:38 UTC
Labels: Area: Build, Won't Fix
