### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by WyattSteinmann** [CosmosOS/Cosmos#3118] opened 2024-12-30 17:47 UTC
**What is the usecase for this plug**
HTTPS Support If You Add To Networking Like Other Methods It Will Make It Easy To Use

**Complexity of plug**
Can this plug be added without requiring new drivers or a lot of work? No As Https Can Be Hard But Make Cosmos Way Better It Will Be A Very Useful Thing

**Describe alternatives you've considered**
Are there workarounds for this plug? No Its Hard To Do But Make Cosmos Way Better

**Additional context**
Just Https

**Comment by valentinbreiz** [comment] 2024-12-30 18:17
Duplicate of https://github.com/CosmosOS/CosmosHttp/issues/1
I close this.

**Closed** 2024-12-30 18:17 UTC
