### ISSUE TITLE
ISOFiles are not added to ISO upon compilation.

### ISSUE THREAD

**Issue by spacebytee** [CosmosOS/Cosmos#2612] opened 2023-03-19 14:35 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
ISOFiles (presumably a bug to do with compilation).

#### Expected Behaviour - What do you think that should happen?
The file is included in the iso upon compilation, and can be read by a VFS.

#### Actual Behaviour - What unexpectedly happens?
The file is not included in the ISO.

#### Reproduction - How did you get this error to appear?
Go on Latest UserKit, include a file in ISOFiles, and compile. It was not recognized by my code, and when looking through the ISO with 7zip, the file wasn't located there either.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest UserKit.

**Comment by 9xbt** [comment] 2023-03-23 07:19
I think the issue is fixed in the latest version of **devkit**. Maybe that could fix it

**Comment by valentinbreiz** [comment] 2023-09-25 12:10
@bytespacegames could you try it? :)

**Closed** 2024-01-05 20:18 UTC
Labels: Bug, Pending User Response
