### ISSUE TITLE
Implement battery percentage detection for laptop users, 

### ISSUE THREAD

**Issue by Samdasti** [CosmosOS/Cosmos#2921] opened 2024-01-24 14:59 UTC
Add this new function - Cosmos.System.Power.GetBatteryPercentage(); - Returns the value of how many percent the battery is, this function only works for laptop users, if the user is running a desktop, it does nothing, this function can be used in an if statement to do something if the battery percentage is of a certain level, for example:
"if (Cosmos.System.Power.GetBatteryPercentage(); == 0) {
    Console.WriteLine("Battery has run out, shutting down...");
    System.Threading.Thread.Sleep(1);
    Cosmos.System.Power.Shutdown();
}
".

**Comment by 9xbt** [comment] 2024-01-24 15:52
Duplicate of https://github.com/CosmosOS/Cosmos/issues/2503

**Closed** 2024-01-24 17:32 UTC
