### ISSUE TITLE
ERROR [COM]: aRC=VBOX_E_VM_ERROR (0x80bb0003) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={Could not take a screenshot (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=-37

### ISSUE THREAD

**Issue by penguin-number-123** [CosmosOS/Cosmos#2142] opened 2022-03-01 06:21 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
Virtual Machine (VBox + Vmware)

#### Expected Behaviour - What do you think that should happen?
The os should boot

#### Actual Behaviour - What unexpectedly happens?
Shows "Memory Initialization"
Guru Meditation, Critical failure
![image](https://user-images.githubusercontent.com/62600889/156116125-23035e9a-a580-4e82-99f9-c351daf355ed.png)

Digging in logs yields 
ERROR [COM]: aRC=VBOX_E_VM_ERROR (0x80bb0003) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={Could not take a screenshot (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=-37
![image](https://user-images.githubusercontent.com/62600889/156115915-0bd585e0-ccb6-403b-81a0-bbffdb1ca7c5.png)

Further analysis shows that there is a strange image with "Now create the kernel class". 
![image](https://user-images.githubusercontent.com/62600889/156115975-f2f96b71-cff2-4ea9-b184-6cbd9c435fd2.png)

Appears to be a screenshot

#### Reproduction - How did you get this error to appear?
I simply do not know
It is fine with default code

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dek kit, updated yesterday.

#### Notes
Compiling to ISO, not direct start with vmware.

**Comment by penguin-number-123** [comment] 2022-03-01 11:48
https://github.com/penguin-number-123/PenguinOS
Code for reference

**Comment by quajak** [comment] 2022-03-01 17:58
Most likely cause is that something is causing the os to crash.

**Comment by MishaTY** [comment] 2022-03-01 21:33
What devkit branch are you using?

**Comment by penguin-number-123** [comment] 2022-03-01 23:11
> What devkit branch are you using?

I really don't know, it was the one that was cloned ereyesterday. It was auto cloned by github desktop.

**Comment by penguin-number-123** [comment] 2022-03-01 23:12
> Most likely cause is that something is causing the os to crash.

I know, but main problem is that... The first line is just a console.writeline statement, and even it doesn't load. Removing the fs.init and register vfs havd no effect.

**Comment by quajak** [comment] 2022-03-02 16:59
> > Most likely cause is that something is causing the os to crash.
> 
> I know, but main problem is that... The first line is just a console.writeline statement, and even it doesn't load. Removing the fs.init and register vfs havd no effect.

Are you initializing any static variables?

**Comment by penguin-number-123** [comment] 2022-03-03 00:22
> > > Most likely cause is that something is causing the os to crash.
> > 
> > 
> > I know, but main problem is that... The first line is just a console.writeline statement, and even it doesn't load. Removing the fs.init and register vfs havd no effect.
> 
> Are you initializing any static variables?

Yes, I am, since I am using a manifest resource stream

**Comment by penguin-number-123** [comment] 2022-03-03 10:10
I commented out the static variable but the error persists.

**Comment by quajak** [comment] 2022-03-03 18:55
I recommend commenting out further parts of the code until it starts working to figure out what the problem is.

**Comment by penguin-number-123** [comment] 2022-03-04 00:15
ok

**Comment by MishaTY** [comment] 2022-03-08 20:50
Closing because not enough info.

**Closed by MishaTY** 2022-03-08 20:50 UTC
Labels: Bug
