### ISSUE TITLE
OS Not start on real PC

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2181] opened 2022-04-06 19:10 UTC
Help please! OS Not starting on real PC
![image](https://user-images.githubusercontent.com/79642857/162050637-fdd3f06a-d029-4787-a62c-715fbdeeea5f.jpg)

**Comment by MishaTY** [comment] 2022-04-06 19:15
Duplicate of #2173

**Closed by MishaTY** 2022-04-06 19:15 UTC
Labels: Bug
