### ISSUE TITLE
Doing a FileSystem operation via an Action makes a CPU Exception and creates a corrupted file

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2459] opened 2022-11-07 09:27 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem

#### Expected Behaviour - What do you think that should happen?
It should create a file like supposed to

#### Actual Behaviour - What unexpectedly happens?
makes a CPU Exception x06 and creates a corrupted directory when its supposed to be a file and sometimes it corrupts the entire filesystem making it unusable
![image](https://user-images.githubusercontent.com/43090601/200274377-ba000b12-d69c-4fe0-87b3-b30ff28e6921.png)

#### Reproduction - How did you get this error to appear?
```cs
if (!Kernel.tryCatch(() => File.WriteAllText(@"0:\fscheck.txt", "This is a test file"), Logger.LogLevel.Fatal))
{
       Logger.Warn("File system checks failed. Disk operations won't be available");
       return;
}
```

`Kernel.tryCatch():`
```cs
public static bool tryCatch(Action action, Logger.LogLevel exceptionLevel)
    {
        try
        {
            action();
        }
        catch (Exception ex)
        {
            Logger.Log(exceptionLevel, ex.Message);
            return false;
        }
        
        return true;
    }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
last devkit as of 7/11/2022

**Comment by Kiirx** [comment] 2022-11-08 18:41
Well it wouldnt be using an action anymore and it will work, the try catch or the logger.log isnt the problem

**Comment by Kiirx** [comment] 2022-11-08 18:59
And I cant use my pc rn![20221108_194450.jpg](https://user-images.githubusercontent.com/43090601/200651651-8193a6ec-7b5f-4533-8130-34a50cb7a831.jpg)

**Comment by AnErrupTion** [comment] 2022-12-19 18:38
After further debugging, it looks like this is caused by System.Enum.GetHashCode(), which currently throws NotImplementedException.

**Comment by quajak** [comment] 2022-12-20 16:37
Closing because we can't reproduce this issue

**Closed by quajak** 2022-12-20 16:37 UTC
Labels: Bug, Up for Grabs, Complexity: Medium, Priority: Medium, Area: Compiler
