### ISSUE TITLE
GUI screen weird display?

### ISSUE THREAD

**Issue by Vortex1134** [CosmosOS/Cosmos#540] opened 2016-12-21 12:23 UTC
So I've followed the tutorial on how to create a gui from cosmos at this link https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI---The-basics. It's giving me a weird display on the screen.

I uploaded what I am receiving. I know the one line is supposed to say "CosmosKernel2 Booted Successfully." As you can see it's just displaying every other letter. As for what's before that. I have no idea. Anybody know why this is happening?

I'm using Visual Studio 2015 Community Edition.

![capture](https://cloud.githubusercontent.com/assets/24697456/21389115/ea210768-c74d-11e6-9287-f60fc7b20fe5.PNG)

**Comment by jp2masa** [comment] 2016-12-21 13:33
Are you using the userkit or the devkit?

**Comment by Vortex1134** [comment] 2016-12-21 13:35
I'm using the devkit, i believe. Had the userkit installed then read that the devkit would be better so I downloaded that and installed that.

**Comment by jp2masa** [comment] 2016-12-21 13:42
VGA doesn't work on the devkit, @fanol is improving graphics. See #514

**Comment by Vortex1134** [comment] 2016-12-21 13:44
Oh bummer. Oh well. So, go back to userkit then?

**Comment by jp2masa** [comment] 2016-12-21 13:51
If you want graphics now, use the userkit(I think you can just install it, without uninstalling the devkit). In the next Cosmos release, graphics will be totally different, so you'll need to change your code if you upgrade at that time.

**Comment by Vortex1134** [comment] 2016-12-21 13:54
Alright, thanks for the quick replies!

**Comment by cjhannah** [comment] 2016-12-21 15:05
graphics doesn't work at all afaik

**Comment by fanoI** [comment] 2016-12-22 10:50
It works only with VBE, I don't think VGA has ever worked and well in any case I think in the end you never need it (YAGNI).

I'm closing this for now the problem is acknowledged and there are multiple duples of this.

**Closed by fanoI** 2016-12-22 10:50 UTC
