### ISSUE TITLE
OpCode 'Stobj' not implemented error

### ISSUE THREAD

**Issue by zdimension** [CosmosOS/Cosmos#103] opened 2015-05-15 15:55 UTC
Hey, I just installed Cosmos User Kit and I'm making a graphics library, but I've got a little problem.
**Image.cs**
```csharp
public Pixel[] Data;
public virtual void Clear(Pixel color)
{
    for (uint i = 0; i < Data.Length; i++)
    {
        Data[i] = color;
    }
}
```
When I try to compile the project, it gives me this error : 
```
Error occurred while invoking IL2CPU.
Exception: System.NotImplementedException: OpCode 'Stobj' not implemented! Encountered in method Void Clear(Paradox.Graphics.Pixel)
   … Cosmos.IL2CPU.ILOpCodes.OpType.GetNumberOfStackPops(MethodBase aMethod) dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpType.cs:ligne 48
   … Cosmos.IL2CPU.ILOpCode.InitStackAnalysis(MethodBase aMethod) dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 296
   … Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILReader.cs:ligne 407
   … Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 533
   … Cosmos.IL2CPU.ILScanner.ScanQueue() dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 658
   … Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 249
   … Cosmos.IL2CPU.CompilerEngine.Execute() dans c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:ligne 238
```
Thanks

**Comment by ARMmaster17** [comment] 2015-05-15 16:09
This has already been fixed in the latest dev kit as part of issue #72 and it's related PR. To fix this, download the latest devkit by going to the code page of this repository and clicking 'Download as .zip'. Unzip the contents of the compressed file to a folder. **CLOSE VISUAL STUDIO**. Then run the .bat file to build it. Multiple windows will pop up, and if you have Windows Vista or later, UAC will prompt you for the administrator password. After that finishes, reopen VS and recompile your project. It should now work. Hope this helps!

**Comment by zdimension** [comment] 2015-05-15 16:22
OK, I have rebuilt the devkit and reinstalled the resulting User Kit, but now when I build the solution, I have this error for project ParadoxBoot (the Cosmos project) :
```
Exception: System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 357
   … Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 698
   … Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 541
   … Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 503
   … Cosmos.IL2CPU.ILScanner.Assemble() dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:ligne 941
   … Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:ligne 257
   … Cosmos.IL2CPU.CompilerEngine.Execute() dans d:\T‚l‚chargements\Cosmos-master (1)\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:ligne 238
```
And I don't know what code is wrong....

**Comment by ARMmaster17** [comment] 2015-05-15 16:23
Seems like someone put in the wrong values for the push/pop actions for the opcode. @PathogenDavid can you go back and confirm this?

**Comment by ARMmaster17** [comment] 2015-05-15 17:59
@zdimension I think it may not have been fully implemented. An OpCode is basically the converted IL code that corresponds to your raw C# code. The problem is there is a bug in breaking down the IL code into Assembly. Hold tight and someone with more experience with IL and ASM will follow up with you.

**Comment by ARMmaster17** [comment] 2015-05-15 18:18
@zdimension, could you post a little bit more of your code on [Gist](http://gist.github.com)? We want to try and trace the problem using some code that's known to trigger the build error.

**Comment by ARMmaster17** [comment] 2015-05-15 18:19
Actually @zdimension, does your code use *Dictionary<>()* or *IDictionary<>()* in it at all?

**Comment by zdimension** [comment] 2015-05-15 18:33
@ARMmaster17 In fact, I don't know what code triggers this, because the error only appears when compiling and it says it's in the file Cosmos.targets in project ParadoxBoot (cosmos project).
And I think it uses both (Dictionary and IDictionary).

**Comment by ARMmaster17** [comment] 2015-05-15 18:35
@zdimension It's an internal error, yes. But I'm asking, does YOUR code use either of those two objects. Those are known to cause similar errors. List<> can also be problematic depending on how it's used.

**Comment by ARMmaster17** [comment] 2015-05-15 18:36
@zdimension It could also be a completely unrelated error since your are using the 'live' DevKit. I'll keep this thread open and notify the project engineers.

**Comment by zdimension** [comment] 2015-05-15 18:40
No I mean my code uses both.

**Comment by ARMmaster17** [comment] 2015-05-15 18:43
Then that is most likely the issue. Either try using a List<> or implement your own version of Dictionary using two object[] variables. This is a known issue and is being worked on as part of our efforts to fix the string library.

**Comment by ARMmaster17** [comment] 2015-05-15 18:49
Then again, I might be completely lost. Check out #72 and what @PathogenDavid had to say about it.

**Comment by mterwoord** [comment] 2015-05-16 09:07
Can you post the definition of Pixel here?

**Comment by zdimension** [comment] 2015-05-16 09:17
Wait, the strange thing is, I tried to delete all my other library projects and all the code calling them, so it's supposed to get me back to the default cosmos project template, but it didn't work either.
I mean I put the code, it was not working, gaving the previous error, then I deleted all the code and it didn't work, as if Cosmos remembered the old (that wasn't present anymore).
(sorry if I doesn't explain great, I'm french)

**Comment by zdimension** [comment] 2015-05-16 09:18
and I'm using Pixel of that https://github.com/CosmosOS/Cosmos/blob/master/Users/Orvid/Orvid.Graphics/Pixel.cs

**Comment by mterwoord** [comment] 2015-05-16 09:18
Have you deleted the references involved as well?

**Comment by zdimension** [comment] 2015-05-16 09:19
Yes, as I have said, I have deleted all the code to come back to the original Cosmos project template code (the text echo thing)
No references, no files, no declarations, nothing.

**Comment by mterwoord** [comment] 2015-05-16 09:36
Can you re-run install.bat?
Other option si to contact me on skype.. Same id as on github.

**Comment by zdimension** [comment] 2015-05-16 09:41
And what does 
```
Exception: System.Exception: Assembly 'Paradox' is in ring User(3). It references assembly 'Cosmos.Core' which is in ring Core(0), but this is not allowed!	ParadoxBoot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31
```
means ?

**Comment by mterwoord** [comment] 2015-05-16 09:43
It's part of our security model, see https://github.com/CosmosOS/Cosmos/blob/master/Docs/Kernel/Levels.md

**Comment by zdimension** [comment] 2015-05-16 09:50
And what should I do if I need Ring.HAL and Ring.System ?

**Comment by mterwoord** [comment] 2015-05-16 09:51
Most kernels will need User. Only driver stuff is in SYstem. HAL stuff is lower-level driver stuff.

**Comment by zdimension** [comment] 2015-05-16 10:17
And 1 times over 3, when I try to debug it tells me that it can't compile because -----Boot.cdb is in use by another process

**Comment by mterwoord** [comment] 2015-05-16 10:19
Please try not to mix multiple things in 1 github issue..  
With latest devkit, can you reproduce the followup issue? (Call tries to pop more stuff ....)

**Comment by zdimension** [comment] 2015-05-16 10:21
I use the latest devkit...
(I downloaded it, ran the "install userkit" thing so it built it and then created my projet)

**Comment by mterwoord** [comment] 2015-05-16 11:38
Yes, but when re-running install.bat, you get the same results? (ie ,the Call tries to pop more stuff... error?)

**Comment by mterwoord** [comment] 2015-06-27 16:09
@zdimension Can you open a new issue if this item is still existing? I'm puzzled on what the actual issue is here..

**Closed by mterwoord** 2015-06-27 16:09 UTC
Labels: area_compiler, bug, priority_high
