### ISSUE TITLE
No Mouse in Door

### ISSUE THREAD

**Issue by simone2014june** [CosmosOS/Cosmos#3071] opened 2024-08-15 18:26 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
The Mouse

#### Expected Behaviour - What do you think that should happen?
Appears the Mouse

#### Actual Behaviour - What unexpectedly happens?
It Dosnet appear

#### Reproduction - How did you get this error to appear?
Using Sys.MouseManger

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest DevKit

**Comment by SzymekkYT** [comment] 2024-08-15 19:08
you didn't provide any code. You only gave us "Using Sys.MouseManger" also it is not a bug... You have to do do your own mouse. In c# nothing really happens just by "using". You just have access to MouseManager class. Please read cosmos documentation, but before learn programming before making an OS even using cosmos.

**Comment by SzymekkYT** [comment] 2024-08-15 19:09
Also what the check is "door"

**Comment by aomine001** [comment] 2024-08-15 19:20
No code = No help.

**Comment by ascpixi** [comment] 2024-08-15 19:27
This is expected behavior. The mouse indeed Dosnes appear in the door. Known locations for mice and other rodents are, for example, the basement, pantry, or walls and insulation.

**Comment by SzymekkYT** [comment] 2024-08-15 19:43
> No code = No help.

sorry, I misunderstood what he wrote. But how do you want mice to show up at his door?
Do you have any summoning egg??

**Comment by blackneeed** [comment] 2024-08-15 19:48
Your friend will not be happy when he sees mice when he opens the door to his house. Why would you expect that? But ok, you can use a summoning egg which you can get by yelling FUCK at 3AM.

**Comment by blackneeed** [comment] 2024-08-15 19:49
Another way is placing cheese next to the door.

**Comment by Eklerka25** [comment] 2024-08-15 19:56
You must create your own mouse form scratch. Collect some of the mouse cells, and manually turn on their oncogenes. Wait a few weeks/months and you have a mouse.

**Comment by Eklerka25** [comment] 2024-08-15 19:58
oh and check if the mouse doesn't have invisibility effect

**Comment by Eklerka25** [comment] 2024-08-15 20:01
oh and i nearly forgot, i stole your mouse

**Comment by 9xbt** [comment] 2024-08-15 20:28
what in the actual fuck is this 😭

**Comment by aomine001** [comment] 2024-08-15 20:29
I'm selling mouse, a black one for $8.99. Contact me at @catflarovich 

:3

**Comment by winksplorer** [comment] 2024-08-15 20:30
> what in the actual fuck is this 😭

I'm not sure what you mean by that, this issue is serious and describes a critical issue in the MouseManger.

**Comment by Samma2009** [comment] 2024-08-15 20:58
if(Code)
{
    Helper.Help();
}
else
{
    Helper.FuckOff()
}

**Comment by Samma2009** [comment] 2024-08-15 21:01
https://music.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Goldjakyt** [comment] 2024-08-15 21:06
if (No_Mouse_in_Door) {
simone2014june.show();
}

**Comment by 9xbt** [comment] 2024-08-15 21:30
> https://music.youtube.com/watch?v=dQw4w9WgXcQ

i have autoplay off >:)

**Comment by blackneeed** [comment] 2024-08-15 21:32
This is a criticial issue, we need to help him get a mouse spawning egg.

**Comment by winksplorer** [comment] 2024-08-15 22:01
> if(Code) { Helper.Help(); } else { Helper.FuckOff() }

you forgot the semicolon

**Comment by GoldenretriverYT** [comment] 2024-08-16 11:47
i think yall scared him away (its better this way)

**Comment by 9xbt** [comment] 2024-08-16 13:32
@MishaProductions just close this

**Comment by MishaProductions** [comment] 2024-08-16 13:33
You need to draw the mouse, mouse manager only provides coordinates.

**Closed by MishaProductions** 2024-08-16 13:33 UTC
Labels: Bug, Invalid

**Comment by SzymekkYT** [comment] 2024-08-16 13:36
for 99.9% he doesnt know how to even make gui nor Console.WriteLine...

**Comment by blackneeed** [comment] 2024-08-16 20:16
No offense but, this is just absolute stupidness on another level. How do you expect anything to start working by importing a library? It's like importing System and thinking it will write Hello World by itself, this is just mad.

**Comment by Simone3838** [comment] 2025-01-01 19:34
😡 simone2014june how dare you!!!
