### ISSUE TITLE
Hangs at: "waiting for debugger connection" when I export as ISO

### ISSUE THREAD

**Issue by RockZombie4** [CosmosOS/Cosmos#2263] opened 2022-05-31 15:16 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
Export as ISO
#### Expected Behaviour - What do you think that should happen?
It should boot my OS

#### Actual Behaviour - What unexpectedly happens?
Hangs at: "waiting for debugger connection" when I export as ISO

#### Reproduction - How did you get this error to appear?
Export as ISO

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by Kiirx** [comment] 2022-05-31 15:28
OH MY GOd

**Comment by Kiirx** [comment] 2022-05-31 15:28
ok I see you're a troll https://github.com/CosmosOS/Cosmos/issues/2262

**Comment by quajak** [comment] 2022-05-31 15:30
Duplicate of #2262

**Closed by quajak** 2022-05-31 15:30 UTC
Labels: Bug
