### ISSUE TITLE
CPU Exception when using StrToByteArray

### ISSUE THREAD

**Issue by EliaSulimanov** [CosmosOS/Cosmos#1333] opened 2020-05-26 16:43 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?
OS

#### Expected Behaviour - What do you think that should happen?
StrToByteArray should return byte array made out of given string

#### Actual Behaviour - What unexpectedly happens?
CPU exception being thrown on run-time.

#### Reproduction - How did you get this error to appear?
I have created new file named log on root dir.
Then, checked its size and got 0 as expected.
Right after that I tried to init new byte array, using StrToByteArray, this is the code:
`byte[] t = ByteToString.StrToByteArray("Hello World!");`

as this line called, I get CPU exception.
tried to debug this line, as soon as I step into, the error appear.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by quajak** [comment] 2020-05-26 21:13
This is a duplicate of #1334

**Comment by EliaSulimanov** [comment] 2020-05-27 05:56
I think the issue #1334 is unrelated to this issue, as the discussion here is about really specific method causing CPU exception, while there the discussion is about wide range behavior related to the way VS2019 is coping with cpu exception.
The issue in #1334 can be reproduced in other ways, as I mentioned there.
I used the same code to show this 2 issues, but other code apply as well on the issue in #1334

**Comment by quajak** [comment] 2020-05-27 11:44
The problem here is that`ByteToString.StrToByteArray` is used to convert strings such as `060050` to `3C-32`. For your case look at using the `Encoding` classes.
The CPU Exception in this case is caused by an uncaught exception.

**Closed** 2020-05-29 10:34 UTC
