### ISSUE TITLE
Cosmos UEFI support

### ISSUE THREAD

**Issue by tANDyeet** [CosmosOS/Cosmos#2737] opened 2023-07-25 14:55 UTC
Hi!
My OS boots on UEFI based laptop when Legacy is on. However on my second UEFI-based laptop there is no Legacy option.

I get "Warning: No console will be available to OS" (when legacy is disabled).

Cosmos version - User Kit 20221121

**Comment by 9xbt** [comment] 2023-07-25 16:11
Cosmos uses BIOS, while modern computers use UEFI. The legacy option on UEFI BIOSes is just to emulate a BIOS so older OSes can run. Cosmos doesn't support UEFI so your OS isn't going to work without legacy being enabled

**Comment by 9xbt** [comment] 2023-07-25 16:12
I don't really know if this is a feature request or a bug report, but I will say that I don't think Cosmos is going to support UEFI soon because of the amount of changes it will need to have for UEFI to work

**Comment by tANDyeet** [comment] 2023-07-25 17:08
Is there any option (workaround) to use it on UEFI? I tried using Ventoy and it didn't work.

**Comment by tANDyeet** [comment] 2023-07-25 17:46
and what is causing Cosmos to not support the UEFI? GRUB or os.bin?

**Comment by valentinbreiz** [comment] 2023-07-26 10:54
Not a bug, I'm closing this.

> and what is causing Cosmos to not support the UEFI? GRUB or os.bin?

UEFI needs a lot of changes, first about the bootloader but we also need some deeper parts like paging or GPT.

**Closed by valentinbreiz** 2023-07-26 10:54 UTC
