### ISSUE TITLE
Unable to find Cosmos Packages

### ISSUE THREAD

**Issue by metsatahe** [CosmosOS/Cosmos#1425] opened 2020-08-07 20:50 UTC
#### Area of Cosmos - What area of Cosmos are we dealing with?

Compiling and writing code

#### Expected Behaviour - What do you think that should happen?

Program should compile and everything should work

#### Actual Behaviour - What unexpectedly happens?

Errors Appear, more specifically

3 NuGet errors:

Error	NU1101	Unable to find package Cosmos.System2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, Package source	CosmosKernel2	

Error	NU1101	Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, Package source	CosmosKernel2	

Error	NU1101	Unable to find package Cosmos.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, Package source	CosmosKernel2

2 errors without an error code::

Error		Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.	CosmosKernel2	

Error		NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.	CosmosKernel2			

#### Reproduction - How did you get this error to appear?

I Installed cosmos with the installer and made a new project in visual studio 2019

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 20200708

**Comment by quajak** [comment] 2020-08-07 20:56
Duplicate of #1420

**Closed by quajak** 2020-08-07 20:56 UTC
