### ISSUE TITLE
CPU Exception after .Contains use in string[]

### ISSUE THREAD

**Issue by HStei** [CosmosOS/Cosmos#2189] opened 2022-04-14 19:25 UTC
#### Expected Behaviour - What do you think that should happen?
'Console.WriteLine("Input found");' if typed input matched with one of the string items.

#### Actual Behaviour - What unexpectedly happens?
Virtual Machine stopped working. Message on screen: CPU Exception x06, Last known address: 0x02244585

#### Reproduction - How did you get this error to appear?
```string[] apps = { "Store", "Editor", "Calculator", "To Do" };
Console.WriteLine("Which apps do you want to pin?");

for(int i = 0; i < 5; i++)
{
     string input = Console.ReadLine();
     if(Apps.Contains(input) == true)
     {
          Console.WriteLine("Input found");
     } else
     {
         Console.WriteLine("Input not found");
     }
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit

**Comment by MishaTY** [comment] 2022-04-21 19:45
Show code of Apps array/list

**Comment by HStei** [comment] 2022-04-23 15:55
string[] Apps = { "Explorer" , "Calc" , "Time" , "Settings" };

**Comment by zarlo** [comment] 2022-04-23 22:36
```csharp
string[] Apps = new string[]{ "Explorer" , "Calc" , "Time" , "Settings" };
```
that should fix it

**Comment by quajak** [comment] 2022-05-01 16:18
> string[] Apps = { "Explorer" , "Calc" , "Time" , "Settings" };

That syntax is fine. The issue is that for .net 5 we had to make the method analyzer ignore generic methods on arrays. This means that the compilation worked fine but at runtime the correct method was not found, leading to the exception you got. The fix for this is to actually support generic methods on arrays. This is done https://github.com/CosmosOS/IL2CPU/pull/111 and this should work once that is merged.

**Closed** 2022-05-02 18:16 UTC
Labels: Bug
