### ISSUE TITLE
Cosmos.Sys.Deboot.Shutdown() at Userkit ?

### ISSUE THREAD

**Issue by indevhero** [CosmosOS/Cosmos#302] opened 2015-12-19 18:28 UTC
I install lastest relese. In many examples there Cosmos.Sys.Reboot.Shutdown (). VS2015C Userkit 20150918. Help me please.

**Comment by fanoI** [comment] 2015-12-21 08:53
The problem is that a lot of examples you find refer to the period before Cosmos was divided in ring. With the new ring system some methods are no more directly accessible from the user ring  ("user" in Cosmso parlance is not the "user" as in the other OS but the Kernel developer itself). So wrapper functions are needed to "link" the shutdown method at low level with the user ring.
In any case the "graceful" shutdown is really needed only if you use mass storage devices so calling the method Stop (ends the Cosmos loop and effectively ends the OS) followed by the Windows 95 text "now you can shutdown the computer" could be sufficient for now...

**Comment by indevhero** [comment] 2015-12-21 18:28
Thank you for your reply.

**Comment by mterwoord** [comment] 2015-12-23 11:56
@indevhero If your question has been answered completely, please close this issue. Thanks!

**Closed** 2015-12-24 18:08 UTC
