### ISSUE TITLE
Cosmos build error ( e_splite3.dll is not loaded)

### ISSUE THREAD

**Issue by FoxCampagna** [CosmosOS/Cosmos#804] opened 2017-11-09 14:19 UTC
Hi, from 5 days i have this error in cosmos: 
Ripristino pacchetti NuGet...
Per impedire che NuGet ripristini i pacchetti durante la compilazione, aprire la finestra i dialogo relativa alle opzioni di Visual Studio, fare clic sul nodo Gestione pacchetti e deselezionare 'Consenti a NuGet di scaricare i pacchetti mancanti durante la compilazione'.

1>------ Inizio compilazione: Progetto: CosmosKernel1, Configurazione: Debug Any CPU ------
1>CosmosKernel1 -> C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netstandard2.0\CosmosKernel1.dll
2>------ Inizio compilazione: Progetto: CosmosKernel1Boot, Configurazione: Debug Any CPU ------
2>	Invoking il2cpu.exe "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\net462\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "References:C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netstandard2.0\CosmosKernel1.dll" "AssemblySearchDirs:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel" 
2>	Executing command line "C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\net462\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "References:C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netstandard2.0\CosmosKernel1.dll" "AssemblySearchDirs:C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel" 
2>	Working directory = 'C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\net462\'
2>	Warning: Loaded : DebugEnabled
2>	Warning: Loaded : StackCorruptionDetectionEnabled
2>	Warning: Loaded : DebugMode
2>	Warning: Loaded : StackCorruptionDetectionLevel
2>	Warning: Loaded : TraceAssemblies
2>	Warning: Loaded : DebugCom
2>	Warning: Loaded : OutputFilename
2>	Warning: Loaded : EnableLogging
2>	Warning: Loaded : EmitDebugSymbols
2>	Warning: Loaded : IgnoreDebugStubAttribute
2>	Warning: Loaded : References
2>	Warning: Loaded : AssemblySearchDirs
2>	Warning: Executing IL2CPU on assembly
2>	Warning: Kernel Base: Cosmos.System.Kernel
2>	Warning: Checking Reference: C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netstandard2.0\CosmosKernel1.dll
2>	Warning:   Exists
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.LOCAL_ARGUMENT_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.INT3Label'
2>	Warning: Executed OK
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:36.7430872
2>	NAsm task took 00:00:04.7810735
2>	Executing command line "C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Build\tools\cygwin\ld.exe" -Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o 'C:/Users/foxch/source/repos/CosmosKernel1/CosmosKernel1/bin/Debug/net462/CosmosKernel1Boot.bin' 'C:/Users/foxch/source/repos/CosmosKernel1/CosmosKernel1/bin/Debug/net462/CosmosKernel1Boot.obj'
2>	Working directory = 'C:\Users\foxch\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\net462\'
2>	Ld task took 00:00:00.1888422
2>C:\Users\foxch\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(75,5): error : An error occurred: System.TypeInitializationException: L'inizializzatore di tipo di 'Microsoft.Data.Sqlite.SqliteConnection' ha generato un'eccezione. ---> System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.DllNotFoundException: Impossibile caricare la DLL 'e_sqlite3': Impossibile trovare il modulo specificato. (Eccezione da HRESULT: 0x8007007E).
2>   in SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
2>   in SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
2>   in SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
2>   in SQLitePCL.Batteries_V2.Init()
2>   --- Fine della traccia dello stack dell'eccezione interna ---
2>   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2>   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2>   in System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2>   in Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
2>   in Microsoft.Data.Sqlite.SqliteConnection..cctor()
2>   --- Fine della traccia dello stack dell'eccezione interna ---
2>   in Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
2>   in Cosmos.Debug.Symbols.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in C:\source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:riga 84
2>   in Cosmos.Debug.Symbols.ObjDump.ExtractMapSymbolsForElfFile(String debugFile, String mapFile) in C:\source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\ObjDump.cs:riga 117
2>   in Cosmos.Build.MSBuild.ExtractMapFromElfFile.Execute() in C:\source\Cosmos\Cosmos\source\Cosmos.Build.MSBuild\ExtractMapFromElfFile.cs:riga 32
2>	Extracting Map file took 00:00:00.3805320
2>Compilazione progetto "CosmosKernel1Boot.Cosmos" NON COMPLETATA.
2>
2>Compilazione NON RIUSCITA.
========== Compilazione: 1 completate, 1 non riuscite, 0 aggiornate, 0 ignorate ==========

The source code:
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel: Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }
        
        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}

Help me please!

**Comment by jp2masa** [comment] 2017-11-09 14:23
This is a duplicate of #796

**Closed** 2017-11-09 19:58 UTC
Labels: Duplicate
