### ISSUE TITLE
SystemVoidSystemIOStreamReaderDisposeSystemBoolean ERROR

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#248] opened 2015-11-11 19:01 UTC
So, whats the problem?
```
Error: Exception: System.Exception: Error compiling method 'SystemVoidSystemIOStreamReaderDisposeSystemBoolean': System.Exception: Error interpreting stacktypes for IL_000A: And ---> System.NotImplementedException: And on types 'System.Boolean' and 'System.Int32' not yet implemented!
4>	   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 748
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
4>	   --- End of inner exception stack trace ---
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
4>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 522 ---> System.Exception: Error interpreting stacktypes for IL_000A: And ---> System.NotImplementedException: And on types 'System.Boolean' and 'System.Int32' not yet implemented!
4>	   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 748
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
4>	   --- End of inner exception stack trace ---
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
4>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
4>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
4>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 522
4>	   --- End of inner exception stack trace ---
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 529
4>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 944
4>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 256
4>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```

**Comment by mterwoord** [comment] 2015-11-18 08:21
Duplicate of #254.

**Closed by mterwoord** 2015-11-18 08:21 UTC
Labels: area_compiler, complexity_low, pending_verification, priority_high
