### ISSUE TITLE
Again, IL2CPU error

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1303] opened 2020-04-18 09:38 UTC
Hello.

I'm trying to use ConsoleGUI framework from NuGet. When i'm building OS, i'm receiving error
"Exception: System.Exception: ", "File: IL2CPU", "String: 1"
Output:
`
1>CosmosKernel2 -> C:\Users\radeber\source\repos\CosmosKernel2\CosmosKernel2\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel2.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\radeber\source\repos\CosmosKernel2\CosmosKernel2\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel2.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.Threading.Interlocked._CompareExchange(System.TypedReference, System.TypedReference, System.Object).
1>  Called from :
1>System.Threading.Interlocked::ConsoleGUI.SizeLimitsChangedHandler CompareExchange[SizeLimitsChangedHandler](ConsoleGUI.SizeLimitsChangedHandler ByRef, ConsoleGUI.SizeLimitsChangedHandler, ConsoleGUI.SizeLimitsChangedHandler)
1>ConsoleGUI.Common.DrawingContext::Void remove_SizeLimitsChanged(ConsoleGUI.SizeLimitsChangedHandler)
1>ConsoleGUI.IDrawingContext::Void remove_SizeLimitsChanged(ConsoleGUI.SizeLimitsChangedHandler)
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:04.7385788
`

**Comment by zarlo** [comment] 2020-04-18 10:50
looks like System.Threading.Interlocked._CompareExchange need to be pluged
there has been no work started on pluging Threading that i know of

**Comment by charlesbetros** [comment] 2020-07-10 18:32
Closing this as it's not a bug. We generally try not to keep issues open for plugs since there many of them not currently implemented.

**Closed by charlesbetros** 2020-07-10 18:32 UTC
Labels: Area: Plugs
