### ISSUE TITLE
Broken background color

### ISSUE THREAD

**Issue by AnotherAltr** [CosmosOS/Cosmos#535] opened 2016-12-18 06:20 UTC
Symbol with a different color appears after each line break :(

![image](https://cloud.githubusercontent.com/assets/13326808/21291921/63f08094-c502-11e6-9a00-ae26cecab27b.png)
Code:
```CSharp
Console.Clear();
// Fill background
Console.BackgroundColor = ConsoleColor.Cyan;
for (int i = 0; i < (80 * 25); i++)
    Console.Write(" ");
Console.CursorTop = 0;
//
while (true)
{
    Console.WriteLine("test!");
    Thread.Sleep(1000);
}
```

But if do not set background color, it's all right:
![image](https://cloud.githubusercontent.com/assets/13326808/21291936/f2aa2696-c502-11e6-8785-6333ad8bf3e8.png)

**Comment by fanoI** [comment] 2016-12-18 15:21
What VM are you using? Bochs or VmWare?

**Comment by AnotherAltr** [comment] 2016-12-18 21:51
VMWare
and
qemu:
![image](https://cloud.githubusercontent.com/assets/13326808/21296818/39f9ed38-c585-11e6-8242-ed66e6e65384.png)
Same problem :\

**Comment by AnotherAltr** [comment] 2016-12-18 22:15
A detailed reaction displaying:
![error](https://cloud.githubusercontent.com/assets/13326808/21296986/85d8bd58-c588-11e6-9fc3-dbfac01cbe85.gif)

**Comment by AnotherAltr** [comment] 2016-12-18 22:17
What do you think about where to look?
In Cosmos.HAL.TextScreen useless to look.

**Comment by AnotherAltr** [comment] 2016-12-19 02:40
Maybe cursor fault?

**Comment by AnotherAltr** [comment] 2016-12-19 03:52
I checked on real hardware, is the same.
![image](https://cloud.githubusercontent.com/assets/13326808/21300715/8d64d6f4-c5b7-11e6-94ca-fd37db23c86f.png)

**Comment by AnotherAltr** [comment] 2016-12-19 04:54
I found!

![image](https://cloud.githubusercontent.com/assets/13326808/21301216/9905d99a-c5bc-11e6-94a3-1753771790f6.png)

TextScreen.SetColors(ConsoleColor, ConsoleColor)
```CSharp
Color = (byte)((uint)(aForeground) | ((uint)(aBackground) << 4));// Success
Color = (byte)((byte)(aForeground) | ((byte)(aBackground) << 4)); // Bug
```
#539

**Comment by AnotherAltr** [comment] 2016-12-19 05:57
Shit! "Broken character" was the color as the background. 
I made a mistake.

It's time to hang himself 
т.т

**Comment by fanoI** [comment] 2016-12-19 09:22
Hmm I can say that I fixed this problem an year ago but I have seen the actual code and I see changes that I don't understand why they have been done...

I had seen that there was problems with the blinking cursor another thing that worked when I finished my work (only in Bochs it seemed a VmWare bug apparently).

**Comment by AnotherAltr** [comment] 2016-12-19 09:37
The same effect
```CSharp
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
//
while (true)
{
    Console.WriteLine("test!");
    Thread.Sleep(1000);
}
```

**Comment by AnotherAltr** [comment] 2016-12-19 09:44
```CSharp
// in Console.cs [Cosmos.System]
protected HAL.TextScreenBase mText {get { return HAL.Global.TextScreen; } }
//
..
Cosmos.HAL.Global.TextScreen.Background = ConsoleColor.DarkRed;
Cosmos.HAL.Global.TextScreen.Foreground = ConsoleColor.Black;
Cosmos.HAL.Global.TextScreen.SetColors(ConsoleColor.Black, ConsoleColor.DarkRed);
Cosmos.HAL.Global.TextScreen.Clear();
while (true)
{
    Console.WriteLine("test!");
    Thread.Sleep(1000);
}
```
The same effect x2

**Comment by fanoI** [comment] 2016-12-19 17:04
I've a doubt are you using the last devKit or UserKit? The UserKit surely is really old and surely had bugs on setBackGround / setForeGround...

**Comment by AnotherAltr** [comment] 2016-12-20 02:11
I am using the latest version devkit

**Comment by fanoI** [comment] 2016-12-20 09:57
OK it was only an hope :-)

Then it is broken again...

**Comment by AnotherAltr** [comment] 2016-12-21 13:16
![image](https://cloud.githubusercontent.com/assets/13326808/21390362/98c52cb0-c797-11e6-9fb9-dd33ad31983e.png)
I tried to use a different method of filling memory

```CSharp

        //in TextScreen [Cosmos.HAL]
        //...
        public override void Clear()
        {
            TextScreenHelpers.Debug("Clearing screen with value ");
            TextScreenHelpers.DebugNumber(mTextClearCellValue);
            //IO.Memory.Fill(mTextClearCellValue);

            for (int i = 0; i < Rows * Cols; i++)
                Console.Write(" ");
            Console.CursorTop = 0;

            mBackgroundClearCellValue = mTextClearCellValue;
        }
```
I suspect that you have a when the memory is full set only color attributes (back\fore)ground
```CSharp
Color = (byte)((uint)(aForeground) | ((uint)(aBackground) << 4));
mTextClearCellValue = (UInt16)(Color << 8 | 0x00);
//...
IO.Memory.Fill(mTextClearCellValue);
```
And the need to set empty symbol?

The decision on the wiki, is set with color symbol :\
```C
void WriteCharacter(unsigned char c, unsigned char forecolour, unsigned char backcolour, int x, int y)
{
     uint16_t attrib = (backcolour << 4) | (forecolour & 0x0F);
     volatile uint16_t * where;
     where = (volatile uint16_t *)0xB8000 + (y * 80 + x) ;
     *where = c | (attrib << 8);
}
```
It may be required such as processing raw memory right?

**Comment by cjhannah** [comment] 2016-12-21 15:07
try replacing uint16_t attrib = (backcolour << 4) | (forecolour & 0x0F) with uint16_t attrib = (forecolour | backcolour << 4);

**Comment by jp2masa** [comment] 2017-01-17 21:25
This issue is hard, because only dark colors(which don't have their higher bit set) will work as background colors.
This is because in the second byte of a VGA char in VGA text mode the first 4 bits set the foreground color and the last 4 bits set the brackground color. However, bit 7(higher bit of background color), can be used to determine whether the char blinks or not. This is a BIOS setting in the case of VGA and EGA and it's enabled by default, but we can't change BIOS settings, so bit 7 of the second byte of the VGA char will always be the blink bit.
Read this for more information: http://webpages.charter.net/danrollins/techhelp/0087.HTM

**Comment by AnotherAltr** [comment] 2017-01-18 06:00
on older versions of Cosmos with terminal color was all right.

**Comment by fanoI** [comment] 2017-01-18 10:05
@jp2masa I confirm that it worked before. I don't understand sincerely what do the modifications you have done that is what was the issue you was trying to solve...

**Comment by jp2masa** [comment] 2017-01-18 11:44
This is so strange, because the screen can be cleared with any background color, but when typing text, the text starts blinking when using colors with the 7th bit set and that blank char appears in front of the text with a different background color.

**Comment by fanoI** [comment] 2017-01-18 17:11
To be clear if the issue that you fixed was that after setting the background / foreground only the new text had the background / foreground changed this is _strangely_ correct as it is the behavior of the Net Framework Console class to make the modification you must call Console.Clear().

I see a lot of differences here respect to mine version (a lot are caused by identation):
https://github.com/CosmosOS/Cosmos/commit/fbac0cabcf7b57ce99a40c5ccb31f52c7eb358ab

in particular I don't like the fact that variable mBackgroundClearCellValue is re-introduced and it has to be "in sync" with mTextClearCellValue.

**Comment by jp2masa** [comment] 2017-01-18 17:17
It's not "in sync" if the screen is not cleared.

**Comment by DjAlEx234** [comment] 2017-03-26 01:29
Did you try `Console.CursorVisible = false;` yet?

**Comment by valentinbreiz** [comment] 2017-05-01 21:45
@DjAlEx234 I tried it does not work.

**Comment by valentinbreiz** [comment] 2017-05-29 22:45
Good new, netcore solves this bug!
![capture](https://cloud.githubusercontent.com/assets/18724279/26563345/22634090-44d1-11e7-9150-4f2341eca8ed.PNG)

**Comment by AnotherAltr** [comment] 2017-05-29 23:33
Hmmm...
I'll check~

**Comment by fanoI** [comment] 2017-05-30 11:12
Really? So it was some subtle low level bug I'd say, as I think the Console does not changed in the Net Core branch...

**Comment by OffensiveCheese** [comment] 2017-05-30 11:16
How strange.

**Comment by valentinbreiz** [comment] 2017-05-30 11:48
@fanoI I was hoping that https://github.com/CosmosOS/Cosmos/issues/624 would have been solved too with netcore but I tried and... I still have this text bug :'(

**Comment by fanoI** [comment] 2017-05-30 12:52
That seems more a "logical" error the good news is that it is really easy to reproduce the Guess demo itself is affected: I've changed it to congratulate with you when the number has been guessed (instead of terminate abruptly) well the text I've written show the bug.

I'm expecting that the Net Core branch has been merged before start to investigate that issue.

**Comment by jp2masa** [comment] 2017-05-30 12:53
I think that #624 is related to the TextScreen implementation, it shouldn't be hard to fix. This issue was probably related to Stind_I1 or Stind_I2.

**Comment by fanoI** [comment] 2017-05-31 07:43
Yes I think so too, it was a low level problem :+1: 

So I close this now.

**Closed by fanoI** 2017-05-31 07:43 UTC
Labels: bug

**Comment by audiotore482** [comment] 2022-12-20 20:44
> Yes I think so too, it was a low level problem 👍
> 
> So I close this now.

Wait what I didn't have time to respond back?
