### ISSUE TITLE
Is there a canvas.drawstring method?

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1725] opened 2021-04-17 14:00 UTC
Is there a canvas.drawstring method?
I installed the lastest userkit and there's no canvas.drawstring or canvas.drawchar method
Please help..
thanks!

**Comment by MishaTY** [comment] 2021-04-17 14:03
The userkit does not have a Canvas.drawstring or Canvas.drawchar method. Install the devkit to get these methods.

**Comment by quajak** [comment] 2021-04-17 16:23
Duplicate of https://github.com/CosmosOS/Cosmos/issues/1723

**Closed by quajak** 2021-04-17 16:23 UTC

**Comment by Vardan2009** [comment] 2021-04-18 10:43
@quajak sorry that I opened two issues :D
